import { QueryRunner, MigrationInterface } from 'typeorm'

import { Kind } from '../breed/entity/kind.entity'
import { Breed } from '../breed/entity/breed.entity'

export class CreateBreedContent implements MigrationInterface {
  public async up(query: QueryRunner) {
    const kind = Kind.CAT

    await query.manager.save(Breed, [
      { key: 'abyssinian', en: 'Abyssinian Cat', pt: 'Gato Abissínio', kind },
      { key: 'aegean', en: 'Aegean Cat', pt: 'Gato Egeu', kind },
      { key: 'american_curl', en: 'American Curl', pt: 'Curl Americano', kind },
      { key: 'american_bobtail', en: 'American Bobtail', pt: 'Bobtail Americano', kind },
      { key: 'american_shorthair', en: 'American Shorthair', pt: 'Pelo Curto Americano', kind },
      { key: 'american_wirehair', en: 'American Wirehair', pt: 'American Wirehair', kind },
      { key: 'arabian_mau', en: 'Arabian Mau', pt: 'Mau Árabe', kind },
      { key: 'australian_mist', en: 'Australian Mist', pt: 'Mist Australiano', kind },
      { key: 'asian', en: 'Asian', pt: 'Asiático', kind },
      { key: 'asian_semi_longhair', en: 'Asian Semi-longhair', pt: 'Asiático de Pelo Semi-Longo', kind },
      { key: 'balinese', en: 'Balinese', pt: 'Balinês', kind },
      { key: 'bambino', en: 'Bambino', pt: 'Bambino', kind },
      { key: 'bengal', en: 'Bengal Cat', pt: 'Bengal', kind },
      { key: 'birman', en: 'Birman', pt: 'Sagrado da Birmânia', kind },
      { key: 'bombay', en: 'Bombay Cat', pt: 'Bombaim', kind },
      { key: 'brazilian_shorthair', en: 'Brazilian Shorthair', pt: 'Gato de Pelo Curto Brasileiro', kind },
      { key: 'british_semi_longhair', en: 'British Semi-longhair', pt: 'British Semi-longhair', kind },
      { key: 'british_shorthair', en: 'British Shorthair', pt: 'Gato de Pelo Curto Inglês', kind },
      { key: 'british_longhair', en: 'British Longhair', pt: 'British Longhair', kind },
      { key: 'burmese', en: 'Burmese Cat', pt: 'Gato Birmanês', kind },
      { key: 'burmilla', en: 'Burmilla', pt: 'Burmilla', kind },
      { key: 'california_spangled', en: 'California Spangled', pt: 'California Spangled', kind },
      { key: 'chantilly_tiffany', en: 'Chantilly-Tiffany', pt: 'Chantilly-Tiffany', kind },
      { key: 'chartreux', en: 'Chartreux', pt: 'Chartreux', kind },
      { key: 'chausie', en: 'Chausie', pt: 'Chausie', kind },
      { key: 'cheetoh', en: 'Cheetoh', pt: 'Cheetoh', kind },
      { key: 'colorpoint_shorthair', en: 'Colorpoint Shorthair', pt: 'Colorpoint Shorthair', kind },
      { key: 'cornish_rex', en: 'Cornish Rex', pt: 'Cornish Rex', kind },
      { key: 'cymric', en: 'Cymric', pt: 'Cymric', kind },
      { key: 'cyprus', en: 'Cyprus Cat', pt: 'Gato de Chipre', kind },
      { key: 'devon_rex', en: 'Devon rex', pt: 'Devon rex', kind },
      { key: 'donskoy', en: 'Donskoy', pt: 'Donskoy', kind },
      { key: 'dragon_li', en: 'Dragon Li', pt: 'Dragão Li', kind },
      { key: 'dwarf_cat', en: 'Dwarf Cat', pt: 'Gato Anão', kind },
      { key: 'egyptian_mau', en: 'Egyptian Mau', pt: 'Mau Egípcio', kind },
      { key: 'european_shorthair', en: 'European Shorthair', pt: 'Gato de Pelo Curto Europeu', kind },
      { key: 'exotic_shorthair', en: 'Exotic Shorthair', pt: 'Gato Exótico', kind },
      { key: 'foldex', en: 'Foldex', pt: 'Foldex', kind },
      { key: 'german_rex', en: 'German Rex', pt: 'Rex Alemão', kind },
      { key: 'havana_brown', en: 'Havana Brown', pt: 'Havana Brown', kind },
      { key: 'highlander', en: 'Highlander', pt: 'Highlander', kind },
      { key: 'himalayan', en: 'Himalayan Cat', pt: 'Himalaio', kind },
      { key: 'japanese_bobtail', en: 'Japanese Bobtail', pt: 'Bobtail japonês', kind },
      { key: 'javanese', en: 'Javanese', pt: 'Javanês', kind },
      { key: 'karelian_bobtail', en: 'Karelian Bobtail', pt: '', kind },
      { key: 'khao_manee', en: 'Khao Manee', pt: 'Khao Manee', kind },
      { key: 'korat', en: 'Korat', pt: 'Korat', kind },
      { key: 'korean_bobtail', en: 'Korean Bobtail', pt: 'Korean Bobtail', kind },
      { key: 'korn_ja', en: 'Korn Ja', pt: 'Korn Ja', kind },
      { key: 'kurilian_bobtail', en: 'Kurilian Bobtail', pt: 'Kurilian Bobtail', kind },
      { key: 'laperm', en: 'LaPerm', pt: 'LaPerm', kind },
      { key: 'lykoi', en: 'Lykoi', pt: 'Lykoi', kind },
      { key: 'maine_coon', en: 'Maine Coon', pt: 'Maine Coon', kind },
      { key: 'manx', en: 'Manx', pt: 'Manx', kind },
      { key: 'mekong_bobtail', en: 'Mekong Bobtail', pt: 'Mekong Bobtail', kind },
      { key: 'minskin', en: 'Minskin', pt: 'Minskin', kind },
      { key: 'munchkin', en: 'Munchkin', pt: 'Munchkin', kind },
      { key: 'nebelung', en: 'Nebelung', pt: 'Nebelung', kind },
      { key: 'napoleon', en: 'Napoleon', pt: 'Napoleon', kind },
      { key: 'norwegian_forest_cat', en: 'Norwegian Forest cat', pt: 'Gato Norueguês da Floresta', kind },
      { key: 'ocicat', en: 'Ocicat', pt: 'Ocicat', kind },
      { key: 'ojos_azules', en: 'Ojos Azules', pt: 'Ojos Azules', kind },
      { key: 'oriental_bicolor', en: 'Oriental Bicolor', pt: 'Bicolor Oriental', kind },
      { key: 'oriental_shorthair', en: 'Oriental Shorthair', pt: 'Oriental Shorthair', kind },
      { key: 'oriental_longhair', en: 'Oriental Longhair', pt: 'Oriental Longhair', kind },
      { key: 'persian_cat', en: 'Persian Cat', pt: 'Persa', kind },
      { key: 'peterbald', en: 'Peterbald', pt: 'Peterbald', kind },
      { key: 'pixie_bob', en: 'Pixie-bob', pt: 'Pixie-bob', kind },
      { key: 'raas', en: 'Raas', pt: 'Raas', kind },
      { key: 'ragamuffin', en: 'Ragamuffin', pt: 'Ragamuffin', kind },
      { key: 'ragdoll', en: 'Ragdoll', pt: 'Ragdoll', kind },
      { key: 'russian_blue', en: 'Russian Blue', pt: 'Gato Azul Russo', kind },
      { key: 'savannah', en: 'Savannah Cat', pt: 'Gato Savannah', kind },
      { key: 'scottish_fold', en: 'Scottish Fold', pt: 'Scottish Fold', kind },
      { key: 'selkirk_rex', en: 'Selkirk Rex', pt: 'Selkirk Rex', kind },
      { key: 'serengeti', en: 'Serengeti Cat', pt: 'Gato Serengeti', kind },
      { key: 'siamese', en: 'Siamese', pt: 'Siamês', kind },
      { key: 'siberian', en: 'Siberian Cat', pt: 'Siberiano', kind },
      { key: 'singapura', en: 'Singapura Cat', pt: 'Singapura', kind },
      { key: 'snowshoe', en: 'Snowshoe', pt: 'Snowshoe', kind },
      { key: 'sokoke', en: 'Sokoke', pt: 'Sokoke', kind },
      { key: 'somali', en: 'Somali Cat', pt: 'Gato Somali', kind },
      { key: 'sphynx', en: 'Sphynx', pt: 'Sphynx', kind },
      { key: 'suphalak', en: 'Suphalak', pt: 'Suphalak', kind },
      { key: 'thai', en: 'Thai', pt: 'Thai', kind },
      { key: 'tonkinese', en: 'Tonkinese Cat', pt: 'Tonquinês', kind },
      { key: 'toyger', en: 'Toyger', pt: 'Toyger', kind },
      { key: 'turkish_angora', en: 'Turkish Angora', pt: 'Angorá', kind },
      { key: 'turkish_van', en: 'Turkish Van', pt: 'Van Turco', kind },
      { key: 'ukrainian_levkoy', en: 'Ukrainian Levkoy', pt: 'Levkoy Ucraniano', kind },
    ])
  }

  public async down(query: QueryRunner) {}
}
