import { QueryRunner, MigrationInterface } from 'typeorm'

import { Kind } from '../breed/entity/kind.entity'
import { Breed } from '../breed/entity/breed.entity'

export class CreateBreedContent implements MigrationInterface {
  public async up(query: QueryRunner) {
    await query.manager.save(Breed, [
      { key: 'abyssinian', en: 'Abyssinian Cat', pt: 'Gato Abissínio', kind: Kind.CAT },
      { key: 'aegean', en: 'Aegean Cat', pt: 'Gato Egeu', kind: Kind.CAT },
      { key: 'american_curl', en: 'American Curl', pt: 'Curl Americano', kind: Kind.CAT },
      { key: 'american_bobtail', en: 'American Bobtail', pt: 'Bobtail Americano', kind: Kind.CAT },
      { key: 'american_shorthair', en: 'American Shorthair', pt: 'Pelo Curto Americano', kind: Kind.CAT },
      { key: 'american_wirehair', en: 'American Wirehair', pt: 'American Wirehair', kind: Kind.CAT },
      { key: 'arabian_mau', en: 'Arabian Mau', pt: 'Mau Árabe', kind: Kind.CAT },
      { key: 'australian_mist', en: 'Australian Mist', pt: 'Mist Australiano', kind: Kind.CAT },
      { key: 'asian', en: 'Asian', pt: 'Asiático', kind: Kind.CAT },
      { key: 'asian_semi_longhair', en: 'Asian Semi-longhair', pt: 'Asiático de Pelo Semi-Longo', kind: Kind.CAT },
      { key: 'balinese', en: 'Balinese', pt: 'Balinês', kind: Kind.CAT },
      { key: 'bambino', en: 'Bambino', pt: 'Bambino', kind: Kind.CAT },
      { key: 'bengal', en: 'Bengal Cat', pt: 'Bengal', kind: Kind.CAT },
      { key: 'birman', en: 'Birman', pt: 'Sagrado da Birmânia', kind: Kind.CAT },
      { key: 'bombay', en: 'Bombay Cat', pt: 'Bombaim', kind: Kind.CAT },
      { key: 'brazilian_shorthair', en: 'Brazilian Shorthair', pt: 'Gato de Pelo Curto Brasileiro', kind: Kind.CAT },
      { key: 'british_semi_longhair', en: 'British Semi-longhair', pt: 'British Semi-longhair', kind: Kind.CAT },
      { key: 'british_shorthair', en: 'British Shorthair', pt: 'Gato de Pelo Curto Inglês', kind: Kind.CAT },
      { key: 'british_longhair', en: 'British Longhair', pt: 'British Longhair', kind: Kind.CAT },
      { key: 'burmese', en: 'Burmese Cat', pt: 'Gato Birmanês', kind: Kind.CAT },
      { key: 'burmilla', en: 'Burmilla', pt: 'Burmilla', kind: Kind.CAT },
      { key: 'california_spangled', en: 'California Spangled', pt: 'California Spangled', kind: Kind.CAT },
      { key: 'chantilly_tiffany', en: 'Chantilly-Tiffany', pt: 'Chantilly-Tiffany', kind: Kind.CAT },
      { key: 'chartreux', en: 'Chartreux', pt: 'Chartreux', kind: Kind.CAT },
      { key: 'chausie', en: 'Chausie', pt: 'Chausie', kind: Kind.CAT },
      { key: 'cheetoh', en: 'Cheetoh', pt: 'Cheetoh', kind: Kind.CAT },
      { key: 'colorpoint_shorthair', en: 'Colorpoint Shorthair', pt: 'Colorpoint Shorthair', kind: Kind.CAT },
      { key: 'cornish_rex', en: 'Cornish Rex', pt: 'Cornish Rex', kind: Kind.CAT },
      { key: 'cymric', en: 'Cymric', pt: 'Cymric', kind: Kind.CAT },
      { key: 'cyprus', en: 'Cyprus Cat', pt: 'Gato de Chipre', kind: Kind.CAT },
      { key: 'devon_rex', en: 'Devon rex', pt: 'Devon rex', kind: Kind.CAT },
      { key: 'donskoy', en: 'Donskoy', pt: 'Donskoy', kind: Kind.CAT },
      { key: 'dragon_li', en: 'Dragon Li', pt: 'Dragão Li', kind: Kind.CAT },
      { key: 'dwarf_cat', en: 'Dwarf Cat', pt: 'Gato Anão', kind: Kind.CAT },
      { key: 'egyptian_mau', en: 'Egyptian Mau', pt: 'Mau Egípcio', kind: Kind.CAT },
      { key: 'european_shorthair', en: 'European Shorthair', pt: 'Gato de Pelo Curto Europeu', kind: Kind.CAT },
      { key: 'exotic_shorthair', en: 'Exotic Shorthair', pt: 'Gato Exótico', kind: Kind.CAT },
      { key: 'foldex', en: 'Foldex', pt: 'Foldex', kind: Kind.CAT },
      { key: 'german_rex', en: 'German Rex', pt: 'Rex Alemão', kind: Kind.CAT },
      { key: 'havana_brown', en: 'Havana Brown', pt: 'Havana Brown', kind: Kind.CAT },
      { key: 'highlander', en: 'Highlander', pt: 'Highlander', kind: Kind.CAT },
      { key: 'himalayan', en: 'Himalayan Cat', pt: 'Himalaio', kind: Kind.CAT },
      { key: 'japanese_bobtail', en: 'Japanese Bobtail', pt: 'Bobtail japonês', kind: Kind.CAT },
      { key: 'javanese', en: 'Javanese', pt: 'Javanês', kind: Kind.CAT },
      { key: 'karelian_bobtail', en: 'Karelian Bobtail', pt: '', kind: Kind.CAT },
      { key: 'khao_manee', en: 'Khao Manee', pt: 'Khao Manee', kind: Kind.CAT },
      { key: 'korat', en: 'Korat', pt: 'Korat', kind: Kind.CAT },
      { key: 'korean_bobtail', en: 'Korean Bobtail', pt: 'Korean Bobtail', kind: Kind.CAT },
      { key: 'korn_ja', en: 'Korn Ja', pt: 'Korn Ja', kind: Kind.CAT },
      { key: 'kurilian_bobtail', en: 'Kurilian Bobtail', pt: 'Kurilian Bobtail', kind: Kind.CAT },
      { key: 'laperm', en: 'LaPerm', pt: 'LaPerm', kind: Kind.CAT },
      { key: 'lykoi', en: 'Lykoi', pt: 'Lykoi', kind: Kind.CAT },
      { key: 'maine_coon', en: 'Maine Coon', pt: 'Maine Coon', kind: Kind.CAT },
      { key: 'manx', en: 'Manx', pt: 'Manx', kind: Kind.CAT },
      { key: 'mekong_bobtail', en: 'Mekong Bobtail', pt: 'Mekong Bobtail', kind: Kind.CAT },
      { key: 'minskin', en: 'Minskin', pt: 'Minskin', kind: Kind.CAT },
      { key: 'munchkin', en: 'Munchkin', pt: 'Munchkin', kind: Kind.CAT },
      { key: 'nebelung', en: 'Nebelung', pt: 'Nebelung', kind: Kind.CAT },
      { key: 'napoleon', en: 'Napoleon', pt: 'Napoleon', kind: Kind.CAT },
      { key: 'norwegian_forest_cat', en: 'Norwegian Forest cat', pt: 'Gato Norueguês da Floresta', kind: Kind.CAT },
      { key: 'ocicat', en: 'Ocicat', pt: 'Ocicat', kind: Kind.CAT },
      { key: 'ojos_azules', en: 'Ojos Azules', pt: 'Ojos Azules', kind: Kind.CAT },
      { key: 'oriental_bicolor', en: 'Oriental Bicolor', pt: 'Bicolor Oriental', kind: Kind.CAT },
      { key: 'oriental_shorthair', en: 'Oriental Shorthair', pt: 'Oriental Shorthair', kind: Kind.CAT },
      { key: 'oriental_longhair', en: 'Oriental Longhair', pt: 'Oriental Longhair', kind: Kind.CAT },
      { key: 'persian_cat', en: 'Persian Cat', pt: 'Persa', kind: Kind.CAT },
      { key: 'peterbald', en: 'Peterbald', pt: 'Peterbald', kind: Kind.CAT },
      { key: 'pixie_bob', en: 'Pixie-bob', pt: 'Pixie-bob', kind: Kind.CAT },
      { key: 'raas', en: 'Raas', pt: 'Raas', kind: Kind.CAT },
      { key: 'ragamuffin', en: 'Ragamuffin', pt: 'Ragamuffin', kind: Kind.CAT },
      { key: 'ragdoll', en: 'Ragdoll', pt: 'Ragdoll', kind: Kind.CAT },
      { key: 'russian_blue', en: 'Russian Blue', pt: 'Gato Azul Russo', kind: Kind.CAT },
      { key: 'savannah', en: 'Savannah Cat', pt: 'Gato Savannah', kind: Kind.CAT },
      { key: 'scottish_fold', en: 'Scottish Fold', pt: 'Scottish Fold', kind: Kind.CAT },
      { key: 'selkirk_rex', en: 'Selkirk Rex', pt: 'Selkirk Rex', kind: Kind.CAT },
      { key: 'serengeti', en: 'Serengeti Cat', pt: 'Gato Serengeti', kind: Kind.CAT },
      { key: 'siamese', en: 'Siamese', pt: 'Siamês', kind: Kind.CAT },
      { key: 'siberian', en: 'Siberian Cat', pt: 'Siberiano', kind: Kind.CAT },
      { key: 'singapura', en: 'Singapura Cat', pt: 'Singapura', kind: Kind.CAT },
      { key: 'snowshoe', en: 'Snowshoe', pt: 'Snowshoe', kind: Kind.CAT },
      { key: 'sokoke', en: 'Sokoke', pt: 'Sokoke', kind: Kind.CAT },
      { key: 'somali', en: 'Somali Cat', pt: 'Gato Somali', kind: Kind.CAT },
      { key: 'sphynx', en: 'Sphynx', pt: 'Sphynx', kind: Kind.CAT },
      { key: 'suphalak', en: 'Suphalak', pt: 'Suphalak', kind: Kind.CAT },
      { key: 'thai', en: 'Thai', pt: 'Thai', kind: Kind.CAT },
      { key: 'tonkinese', en: 'Tonkinese Cat', pt: 'Tonquinês', kind: Kind.CAT },
      { key: 'toyger', en: 'Toyger', pt: 'Toyger', kind: Kind.CAT },
      { key: 'turkish_angora', en: 'Turkish Angora', pt: 'Angorá', kind: Kind.CAT },
      { key: 'turkish_van', en: 'Turkish Van', pt: 'Van Turco', kind: Kind.CAT },
      { key: 'ukrainian_levkoy', en: 'Ukrainian Levkoy', pt: 'Levkoy Ucraniano', kind: Kind.CAT },
    ])

    await query.manager.save(Breed, [
      { key: 'affenpinscher', en: '', pt: '', kind: Kind.DOG },
      { key: 'afghan_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'afghan_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'aidi', en: '', pt: '', kind: Kind.DOG },
      { key: 'airedale_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'akbash', en: '', pt: '', kind: Kind.DOG },
      { key: 'akita', en: '', pt: '', kind: Kind.DOG },
      { key: 'alano_español', en: '', pt: '', kind: Kind.DOG },
      { key: 'alaskan_husky', en: '', pt: '', kind: Kind.DOG },
      { key: 'alaskan_klee_kai', en: '', pt: '', kind: Kind.DOG },
      { key: 'alaskan_malamute', en: '', pt: '', kind: Kind.DOG },
      { key: 'alaunt', en: '', pt: '', kind: Kind.DOG },
      { key: 'alopekis', en: '', pt: '', kind: Kind.DOG },
      { key: 'alpine_dachsbracke', en: '', pt: '', kind: Kind.DOG },
      { key: 'alpine_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'alpine_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_akita', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_bulldog', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_cocker_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_english_coonhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_eskimo_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_foxhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_hairless_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_pit_bull_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_staffordshire_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'american_water_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'anatolian_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'andalusian_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'anglo_français_de_petite_vénerie', en: '', pt: '', kind: Kind.DOG },
      { key: 'appenzeller_sennenhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_de_lAriege', en: '', pt: '', kind: Kind.DOG },
      { key: 'ariegeois', en: '', pt: '', kind: Kind.DOG },
      { key: 'armant', en: '', pt: '', kind: Kind.DOG },
      { key: 'armenian_gampr_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'artois_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_cattle_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_kelpie', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_silky_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_stumpy_tail_cattle_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'australian_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'austrian_black_and_tan_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'austrian_pinscher', en: '', pt: '', kind: Kind.DOG },
      { key: 'azawakh', en: '', pt: '', kind: Kind.DOG },
      { key: 'bakharwal_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'barbet', en: '', pt: '', kind: Kind.DOG },
      { key: 'basenji', en: '', pt: '', kind: Kind.DOG },
      { key: 'basque_ratter', en: '', pt: '', kind: Kind.DOG },
      { key: 'basque_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_artésien_normand', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_bleu_de_gascogne', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_fauve_de_bretagne', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_griffon_vendéen_grand', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_griffon_vendéen_petit', en: '', pt: '', kind: Kind.DOG },
      { key: 'basset_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'bavarian_mountain_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'beagle', en: '', pt: '', kind: Kind.DOG },
      { key: 'beagle_harrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'bearded_collie', en: '', pt: '', kind: Kind.DOG },
      { key: 'beauceron', en: '', pt: '', kind: Kind.DOG },
      { key: 'bedlington_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_groenendael', en: '', pt: '', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_laekenois', en: '', pt: '', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_malinois', en: '', pt: '', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_tervuren', en: '', pt: '', kind: Kind.DOG },
      { key: 'bergamasco_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'berger_blanc_suisse', en: '', pt: '', kind: Kind.DOG },
      { key: 'berger_picard', en: '', pt: '', kind: Kind.DOG },
      { key: 'bernese_mountain_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'bichon_frise', en: '', pt: '', kind: Kind.DOG },
      { key: 'billy', en: '', pt: '', kind: Kind.DOG },
      { key: 'black_and_tan_coonhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'black_and_tan_virginia_foxhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'black_norwegian_elkhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'black_russian_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'black_mouth_cur', en: '', pt: '', kind: Kind.DOG },
      { key: 'bleu_de_gascogne_grand', en: '', pt: '', kind: Kind.DOG },
      { key: 'bleu_de_gascogne_petit', en: '', pt: '', kind: Kind.DOG },
      { key: 'bloodhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'blue_heeler', en: '', pt: '', kind: Kind.DOG },
      { key: 'blue_lacy', en: '', pt: '', kind: Kind.DOG },
      { key: 'blue_paul_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'blue_picardy_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'bluetick_coonhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'boerboel', en: '', pt: '', kind: Kind.DOG },
      { key: 'bohemian_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'bolognese', en: '', pt: '', kind: Kind.DOG },
      { key: 'border_collie', en: '', pt: '', kind: Kind.DOG },
      { key: 'border_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'borzoi', en: '', pt: '', kind: Kind.DOG },
      { key: 'bosnian_coarse_haired_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'boston_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'bouvier_des_ardennes', en: '', pt: '', kind: Kind.DOG },
      { key: 'bouvier_des_flandres', en: '', pt: '', kind: Kind.DOG },
      { key: 'boxer', en: '', pt: '', kind: Kind.DOG },
      { key: 'boykin_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'bracco_italiano', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_dAuvergne', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_du_bourbonnais', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_du_puy', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_francais', en: '', pt: '', kind: Kind.DOG },
      { key: 'braque_saint_germain', en: '', pt: '', kind: Kind.DOG },
      { key: 'brazilian_dogo', en: '', pt: '', kind: Kind.DOG },
      { key: 'brazilian_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'briard', en: '', pt: '', kind: Kind.DOG },
      { key: 'briquet_griffon_vendéen', en: '', pt: '', kind: Kind.DOG },
      { key: 'brittany', en: '', pt: '', kind: Kind.DOG },
      { key: 'broholmer', en: '', pt: '', kind: Kind.DOG },
      { key: 'bruno_jura_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'bucovina_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'bull_and_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'bull_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'bull_terrier_miniature', en: '', pt: '', kind: Kind.DOG },
      { key: 'bulldog', en: '', pt: '', kind: Kind.DOG },
      { key: 'bullenbeisser', en: '', pt: '', kind: Kind.DOG },
      { key: 'bullmastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'bully_kutta', en: '', pt: '', kind: Kind.DOG },
      { key: 'burgos_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'cairn_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'canaan_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'canadian_eskimo_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'cane_corso', en: '', pt: '', kind: Kind.DOG },
      { key: 'cantabrian_water_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'cao_da_Serra_de_aires', en: '', pt: '', kind: Kind.DOG },
      { key: 'cao_de_castro_laboreiro', en: '', pt: '', kind: Kind.DOG },
      { key: 'cao_de_gado_transmontano', en: '', pt: '', kind: Kind.DOG },
      { key: 'cao_fila_de_sao_miguel', en: '', pt: '', kind: Kind.DOG },
      { key: 'carolina dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'carpathian_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'catahoula_leopard_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'catalan_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'caucasian_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'cavalier_king_charles_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'central_asian_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'cesky_fousek', en: '', pt: '', kind: Kind.DOG },
      { key: 'cesky_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'chesapeake_bay_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'chien_français_blanc_et_noir', en: '', pt: '', kind: Kind.DOG },
      { key: 'chien_français_blanc_et_orange', en: '', pt: '', kind: Kind.DOG },
      { key: 'chien_français_tricolore', en: '', pt: '', kind: Kind.DOG },
      { key: 'chien_gris', en: '', pt: '', kind: Kind.DOG },
      { key: 'chihuahua', en: '', pt: '', kind: Kind.DOG },
      { key: 'chilean_fox_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'chinese_chongqing_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'chinese_crested_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'chinese_imperial_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'chinook', en: '', pt: '', kind: Kind.DOG },
      { key: 'chippiparai', en: '', pt: '', kind: Kind.DOG },
      { key: 'chow_chow', en: '', pt: '', kind: Kind.DOG },
      { key: 'cierny_sery', en: '', pt: '', kind: Kind.DOG },
      { key: 'cirneco_dellEtna', en: '', pt: '', kind: Kind.DOG },
      { key: 'clumber_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'collie_rough', en: '', pt: '', kind: Kind.DOG },
      { key: 'collie_smooth', en: '', pt: '', kind: Kind.DOG },
      { key: 'combai', en: '', pt: '', kind: Kind.DOG },
      { key: 'cordoba_fighting_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'coton_de_tulear', en: '', pt: '', kind: Kind.DOG },
      { key: 'cretan_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'croatian_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'cumberland_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'curly_coated_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'cursinu', en: '', pt: '', kind: Kind.DOG },
      { key: 'czechoslovakian_wolfdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'dachshund', en: '', pt: '', kind: Kind.DOG },
      { key: 'dalmatian', en: '', pt: '', kind: Kind.DOG },
      { key: 'dandie_dinmont_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'danish_swedish_farmdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'deutsche_bracke', en: '', pt: '', kind: Kind.DOG },
      { key: 'doberman_pinscher', en: '', pt: '', kind: Kind.DOG },
      { key: 'dogo_argentino', en: '', pt: '', kind: Kind.DOG },
      { key: 'dogo_cubano', en: '', pt: '', kind: Kind.DOG },
      { key: 'dogue_de_bordeaux', en: '', pt: '', kind: Kind.DOG },
      { key: 'drentse_patrijshond', en: '', pt: '', kind: Kind.DOG },
      { key: 'drever', en: '', pt: '', kind: Kind.DOG },
      { key: 'dunker', en: '', pt: '', kind: Kind.DOG },
      { key: 'dutch_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'dutch_smoushond', en: '', pt: '', kind: Kind.DOG },
      { key: 'east_siberian_laika', en: '', pt: '', kind: Kind.DOG },
      { key: 'east_european_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'elo', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_cocker_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_foxhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_setter', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_springer_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_toy_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_water_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'english_white_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'entlebucher_mountain_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'estonian_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'estrela_mountain_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'eurasier', en: '', pt: '', kind: Kind.DOG },
      { key: 'eurohound', en: '', pt: '', kind: Kind.DOG },
      { key: 'field_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'fila_brasileiro', en: '', pt: '', kind: Kind.DOG },
      { key: 'finnish_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'finnish_lapphund', en: '', pt: '', kind: Kind.DOG },
      { key: 'finnish_spitz', en: '', pt: '', kind: Kind.DOG },
      { key: 'flat_coated_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'fox_terrier_smooth', en: '', pt: '', kind: Kind.DOG },
      { key: 'fox_terrier_wire', en: '', pt: '', kind: Kind.DOG },
      { key: 'french_brittany', en: '', pt: '', kind: Kind.DOG },
      { key: 'french_bulldog', en: '', pt: '', kind: Kind.DOG },
      { key: 'french_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'gaddi_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'galgo_espanol', en: '', pt: '', kind: Kind.DOG },
      { key: 'galician_cattle_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'garafian_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'gascon_saintongeois', en: '', pt: '', kind: Kind.DOG },
      { key: 'georgian_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_longhaired_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_pinscher', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_roughhaired_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_shorthaired_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_spitz', en: '', pt: '', kind: Kind.DOG },
      { key: 'german_wirehaired_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'giant_schnauzer', en: '', pt: '', kind: Kind.DOG },
      { key: 'glen_of_imaal_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'golden_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'gordon_setter', en: '', pt: '', kind: Kind.DOG },
      { key: 'gran_mastín_de_borínquen', en: '', pt: '', kind: Kind.DOG },
      { key: 'grand_anglo_français_blanc_et_noir', en: '', pt: '', kind: Kind.DOG },
      { key: 'grand_anglo_français_blanc_et_orange', en: '', pt: '', kind: Kind.DOG },
      { key: 'grand_anglo_français_tricolore', en: '', pt: '', kind: Kind.DOG },
      { key: 'grand_griffon_vendeen', en: '', pt: '', kind: Kind.DOG },
      { key: 'great_dane', en: '', pt: '', kind: Kind.DOG },
      { key: 'great_pyrenees', en: '', pt: '', kind: Kind.DOG },
      { key: 'greater_swiss_mountain_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'hellenic_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'greenland_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'greyhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'griffon_bleu_de_gascogne', en: '', pt: '', kind: Kind.DOG },
      { key: 'griffon_bruxellois', en: '', pt: '', kind: Kind.DOG },
      { key: 'griffon_fauve_de_bretagne', en: '', pt: '', kind: Kind.DOG },
      { key: 'griffon_nivernais', en: '', pt: '', kind: Kind.DOG },
      { key: 'guatemalan_dogo', en: '', pt: '', kind: Kind.DOG },
      { key: 'hamiltonstovare', en: '', pt: '', kind: Kind.DOG },
      { key: 'hanover_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'hare_indian_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'harrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'havanese', en: '', pt: '', kind: Kind.DOG },
      { key: 'hawaiian_poi_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'himalayan_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'hokkaido', en: '', pt: '', kind: Kind.DOG },
      { key: 'hortaya_borzaya', en: '', pt: '', kind: Kind.DOG },
      { key: 'hovawart', en: '', pt: '', kind: Kind.DOG },
      { key: 'huntaway', en: '', pt: '', kind: Kind.DOG },
      { key: 'hygenhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'ibizan_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'icelandic_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'indian_pariah_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'indian_spitz', en: '', pt: '', kind: Kind.DOG },
      { key: 'irish_red_and_white_setter', en: '', pt: '', kind: Kind.DOG },
      { key: 'irish_setter', en: '', pt: '', kind: Kind.DOG },
      { key: 'irish_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'irish_water_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'irish_wolfhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'istrian_coarse_haired_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'istrian_shorthaired_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'italian_greyhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'jack_russell_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'jagdterrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'jamthund', en: '', pt: '', kind: Kind.DOG },
      { key: 'japanese_chin', en: '', pt: '', kind: Kind.DOG },
      { key: 'japanese_spitz', en: '', pt: '', kind: Kind.DOG },
      { key: 'japanese_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'kaikadi', en: '', pt: '', kind: Kind.DOG },
      { key: 'kai_ken', en: '', pt: '', kind: Kind.DOG },
      { key: 'kangal_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'kanni', en: '', pt: '', kind: Kind.DOG },
      { key: 'karakachan_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'karelian_bear_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'karst_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'keeshond', en: '', pt: '', kind: Kind.DOG },
      { key: 'kerry_beagle', en: '', pt: '', kind: Kind.DOG },
      { key: 'kerry_blue_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'king_charles_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'king_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'kintamani', en: '', pt: '', kind: Kind.DOG },
      { key: 'kishu_ken', en: '', pt: '', kind: Kind.DOG },
      { key: 'komondor', en: '', pt: '', kind: Kind.DOG },
      { key: 'kooikerhondje', en: '', pt: '', kind: Kind.DOG },
      { key: 'koolie', en: '', pt: '', kind: Kind.DOG },
      { key: 'korean_jindo', en: '', pt: '', kind: Kind.DOG },
      { key: 'kromfohrlander', en: '', pt: '', kind: Kind.DOG },
      { key: 'kumaon_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'kunming_wolfdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'kuri', en: '', pt: '', kind: Kind.DOG },
      { key: 'kuvasz', en: '', pt: '', kind: Kind.DOG },
      { key: 'kyi_Leo', en: '', pt: '', kind: Kind.DOG },
      { key: 'labrador_husky', en: '', pt: '', kind: Kind.DOG },
      { key: 'labrador_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'lagotto_romagnolo', en: '', pt: '', kind: Kind.DOG },
      { key: 'lakeland_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'lancashire_heeler', en: '', pt: '', kind: Kind.DOG },
      { key: 'landseer', en: '', pt: '', kind: Kind.DOG },
      { key: 'lapponian_herder', en: '', pt: '', kind: Kind.DOG },
      { key: 'leonberger', en: '', pt: '', kind: Kind.DOG },
      { key: 'lhasa_apso', en: '', pt: '', kind: Kind.DOG },
      { key: 'lithuanian_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'lowchen', en: '', pt: '', kind: Kind.DOG },
      { key: 'mackenzie_river_husky', en: '', pt: '', kind: Kind.DOG },
      { key: 'magyar_agar', en: '', pt: '', kind: Kind.DOG },
      { key: 'mahratta_greyhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'majorca_ratter', en: '', pt: '', kind: Kind.DOG },
      { key: 'majorca_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'maltese', en: '', pt: '', kind: Kind.DOG },
      { key: 'manchester_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'maremma_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'mcNab', en: '', pt: '', kind: Kind.DOG },
      { key: 'mexican_hairless_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_australian_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_american_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_fox_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_pinscher', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_schnauzer', en: '', pt: '', kind: Kind.DOG },
      { key: 'miniature_shar_pei', en: '', pt: '', kind: Kind.DOG },
      { key: 'romanian_mioritic_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'molossus', en: '', pt: '', kind: Kind.DOG },
      { key: 'molossus_of_epirus', en: '', pt: '', kind: Kind.DOG },
      { key: 'montenegrin_mountain_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'moscow_watchdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'moscow_water_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'mountain_cur', en: '', pt: '', kind: Kind.DOG },
      { key: 'mucuchies', en: '', pt: '', kind: Kind.DOG },
      { key: 'mudhol_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'mudi', en: '', pt: '', kind: Kind.DOG },
      { key: 'munsterlander_large', en: '', pt: '', kind: Kind.DOG },
      { key: 'munsterländer_small', en: '', pt: '', kind: Kind.DOG },
      { key: 'neapolitan_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'newfoundland', en: '', pt: '', kind: Kind.DOG },
      { key: 'new_zealand_heading_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'norfolk_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'norfolk_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'norrbottenspets', en: '', pt: '', kind: Kind.DOG },
      { key: 'north_country_beagle', en: '', pt: '', kind: Kind.DOG },
      { key: 'northern_inuit_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'norwegian_buhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'norwegian_elkhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'norwegian_lundehund', en: '', pt: '', kind: Kind.DOG },
      { key: 'norwich_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'nova_scotia_duck_tolling_retriever', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_croatian_sighthound', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_danish_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_english_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_english_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_german_shepherd_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'old_time_farm_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'olde_english_bulldogge', en: '', pt: '', kind: Kind.DOG },
      { key: 'otterhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'pachon_navarro', en: '', pt: '', kind: Kind.DOG },
      { key: 'pandikona_hunting_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'paisley_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'papillon', en: '', pt: '', kind: Kind.DOG },
      { key: 'parson_russell_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'patterdale_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'pekingese', en: '', pt: '', kind: Kind.DOG },
      { key: 'perro_de_presa_canario', en: '', pt: '', kind: Kind.DOG },
      { key: 'perro_de_presa_mallorquin', en: '', pt: '', kind: Kind.DOG },
      { key: 'peruvian_hairless_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'phalene', en: '', pt: '', kind: Kind.DOG },
      { key: 'pharaoh_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'phu_quoc_ridgeback', en: '', pt: '', kind: Kind.DOG },
      { key: 'picardy_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'plummer_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'plott_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'podenco_canario', en: '', pt: '', kind: Kind.DOG },
      { key: 'pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'poitevin', en: '', pt: '', kind: Kind.DOG },
      { key: 'polish_greyhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'polish_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'polish_hunting_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'polish_lowland_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'polish_tatra_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'pomeranian', en: '', pt: '', kind: Kind.DOG },
      { key: 'pont_audemer_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'poodle', en: '', pt: '', kind: Kind.DOG },
      { key: 'porcelaine', en: '', pt: '', kind: Kind.DOG },
      { key: 'portuguese_podengo', en: '', pt: '', kind: Kind.DOG },
      { key: 'portuguese_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'portuguese_water_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'posavac_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'prazsky_krysarik', en: '', pt: '', kind: Kind.DOG },
      { key: 'pudelpointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'pug', en: '', pt: '', kind: Kind.DOG },
      { key: 'puli', en: '', pt: '', kind: Kind.DOG },
      { key: 'pumi', en: '', pt: '', kind: Kind.DOG },
      { key: 'pungsan_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'pyrenean_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'pyrenean_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'rafeiro_do_alentejo', en: '', pt: '', kind: Kind.DOG },
      { key: 'rajapalayam', en: '', pt: '', kind: Kind.DOG },
      { key: 'rampur_greyhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'rastreador_brasileiro', en: '', pt: '', kind: Kind.DOG },
      { key: 'ratonero_bodeguero_andaluz', en: '', pt: '', kind: Kind.DOG },
      { key: 'ratonero_murciano_de_huerta', en: '', pt: '', kind: Kind.DOG },
      { key: 'ratonero_valenciano', en: '', pt: '', kind: Kind.DOG },
      { key: 'rat_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'redbone_coonhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'rhodesian_ridgeback', en: '', pt: '', kind: Kind.DOG },
      { key: 'rottweiler', en: '', pt: '', kind: Kind.DOG },
      { key: 'russian_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'russian_toy', en: '', pt: '', kind: Kind.DOG },
      { key: 'russian_tracker', en: '', pt: '', kind: Kind.DOG },
      { key: 'russo_european_laika', en: '', pt: '', kind: Kind.DOG },
      { key: 'russell_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'saarloos_wolfdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'sabueso_espanol', en: '', pt: '', kind: Kind.DOG },
      { key: 'sabueso_fino_colombiano', en: '', pt: '', kind: Kind.DOG },
      { key: 'saint_usuge_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'sakhalin_husky', en: '', pt: '', kind: Kind.DOG },
      { key: 'saluki', en: '', pt: '', kind: Kind.DOG },
      { key: 'samoyed', en: '', pt: '', kind: Kind.DOG },
      { key: 'sapsali', en: '', pt: '', kind: Kind.DOG },
      { key: 'sarplaninac', en: '', pt: '', kind: Kind.DOG },
      { key: 'schapendoes', en: '', pt: '', kind: Kind.DOG },
      { key: 'schillerstövare', en: '', pt: '', kind: Kind.DOG },
      { key: 'schipperke', en: '', pt: '', kind: Kind.DOG },
      { key: 'standard_schnauzer', en: '', pt: '', kind: Kind.DOG },
      { key: 'schweizer_laufhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'schweizerischer_niederlaufhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'scotch_collie', en: '', pt: '', kind: Kind.DOG },
      { key: 'scottish_deerhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'scottish_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'sealyham_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'segugio_italiano', en: '', pt: '', kind: Kind.DOG },
      { key: 'seppala_siberian_sleddog', en: '', pt: '', kind: Kind.DOG },
      { key: 'serbian_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'serbian_tricolour_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'seskar_seal_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'shar_pei', en: '', pt: '', kind: Kind.DOG },
      { key: 'shetland_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'shiba_inu', en: '', pt: '', kind: Kind.DOG },
      { key: 'shih_tzu', en: '', pt: '', kind: Kind.DOG },
      { key: 'shikoku', en: '', pt: '', kind: Kind.DOG },
      { key: 'shiloh_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'siberian_husky', en: '', pt: '', kind: Kind.DOG },
      { key: 'silken_windhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'sinhala_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'skye_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'sloughi', en: '', pt: '', kind: Kind.DOG },
      { key: 'slovak_cuvac', en: '', pt: '', kind: Kind.DOG },
      { key: 'slovakian_rough_haired_pointer', en: '', pt: '', kind: Kind.DOG },
      { key: 'slovensky_kopov', en: '', pt: '', kind: Kind.DOG },
      { key: 'smalandsstovare', en: '', pt: '', kind: Kind.DOG },
      { key: 'small_greek_domestic_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'soft_coated_wheaten_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'south_russian_ovcharka', en: '', pt: '', kind: Kind.DOG },
      { key: 'southern_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'spanish_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'spanish_water_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'spinone_italiano', en: '', pt: '', kind: Kind.DOG },
      { key: 'sporting_lucas_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'st_bernard', en: '', pt: '', kind: Kind.DOG },
      { key: 'st_johns_water_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'stabyhoun', en: '', pt: '', kind: Kind.DOG },
      { key: 'staffordshire_bull_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'stephens_cur', en: '', pt: '', kind: Kind.DOG },
      { key: 'styrian_coarse_haired_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'sussex_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'swedish_lapphund', en: '', pt: '', kind: Kind.DOG },
      { key: 'swedish_vallhund', en: '', pt: '', kind: Kind.DOG },
      { key: 'tahltan_bear_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'taigan', en: '', pt: '', kind: Kind.DOG },
      { key: 'taiwan_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'talbot', en: '', pt: '', kind: Kind.DOG },
      { key: 'tamaskan_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'teddy_roosevelt_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'telomian', en: '', pt: '', kind: Kind.DOG },
      { key: 'tenterfield_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'terceira_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'thai_bangkaew_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'thai_ridgeback', en: '', pt: '', kind: Kind.DOG },
      { key: 'tibetan_mastiff', en: '', pt: '', kind: Kind.DOG },
      { key: 'tibetan_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'tibetan_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'tornjak', en: '', pt: '', kind: Kind.DOG },
      { key: 'tosa', en: '', pt: '', kind: Kind.DOG },
      { key: 'toy_bulldog', en: '', pt: '', kind: Kind.DOG },
      { key: 'toy_fox_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'toy_manchester_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'toy_trawler_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'transylvanian_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'treeing_cur', en: '', pt: '', kind: Kind.DOG },
      { key: 'treeing_tennessee_brindle', en: '', pt: '', kind: Kind.DOG },
      { key: 'treeing_walker_coonhound', en: '', pt: '', kind: Kind.DOG },
      { key: 'trigg_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'tweed_water_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'tyrolean_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'cimarron_uruguayo', en: '', pt: '', kind: Kind.DOG },
      { key: 'valencian_ratter', en: '', pt: '', kind: Kind.DOG },
      { key: 'vanjari_hound', en: '', pt: '', kind: Kind.DOG },
      { key: 'villano_de_las_encartaciones', en: '', pt: '', kind: Kind.DOG },
      { key: 'vizsla', en: '', pt: '', kind: Kind.DOG },
      { key: 'volpino_italiano', en: '', pt: '', kind: Kind.DOG },
      { key: 'weimaraner', en: '', pt: '', kind: Kind.DOG },
      { key: 'welsh_corgi_cardigan', en: '', pt: '', kind: Kind.DOG },
      { key: 'welsh_corgi_pembroke', en: '', pt: '', kind: Kind.DOG },
      { key: 'welsh_sheepdog', en: '', pt: '', kind: Kind.DOG },
      { key: 'welsh_springer_spaniel', en: '', pt: '', kind: Kind.DOG },
      { key: 'welsh_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'west_highland_white_terrier', en: '', pt: '', kind: Kind.DOG },
      { key: 'west_siberian_laika', en: '', pt: '', kind: Kind.DOG },
      { key: 'westphalian_dachsbracke', en: '', pt: '', kind: Kind.DOG },
      { key: 'wetterhoun', en: '', pt: '', kind: Kind.DOG },
      { key: 'whippet', en: '', pt: '', kind: Kind.DOG },
      { key: 'white_shepherd', en: '', pt: '', kind: Kind.DOG },
      { key: 'wirehaired_pointing_griffon', en: '', pt: '', kind: Kind.DOG },
      { key: 'wirehaired_vizsla', en: '', pt: '', kind: Kind.DOG },
      { key: 'xiasi_dog', en: '', pt: '', kind: Kind.DOG },
      { key: 'yorkshire_terrier', en: '', pt: '', kind: Kind.DOG },
    ])
  }

  public async down(query: QueryRunner) {
    await query.clearTable('breed')
  }
}
