import { QueryRunner, MigrationInterface } from 'typeorm'

import { Kind } from '../breed/entity/kind.entity'
import { Breed } from '../breed/entity/breed.entity'

export class CreateBreedContent implements MigrationInterface {
  public async up(query: QueryRunner) {
    const kind = Kind.CAT

    await query.manager.save(Breed, [
      { key: 'abyssinian', en: '', pt: '', kind },
      { key: 'aegean', en: '', pt: '', kind },
      { key: 'american_curl', en: '', pt: '', kind },
      { key: 'american_bobtail', en: '', pt: '', kind },
      { key: 'american_shorthair', en: '', pt: '', kind },
      { key: 'american_wirehair', en: '', pt: '', kind },
      { key: 'arabian_mau', en: '', pt: '', kind },
      { key: 'australian_mist', en: '', pt: '', kind },
      { key: 'asian', en: '', pt: '', kind },
      { key: 'asian_semi_longhair', en: '', pt: '', kind },
      { key: 'balinese', en: '', pt: '', kind },
      { key: 'bambino', en: '', pt: '', kind },
      { key: 'bengal', en: '', pt: '', kind },
      { key: 'birman', en: '', pt: '', kind },
      { key: 'bombay', en: '', pt: '', kind },
      { key: 'brazilian_shorthair', en: '', pt: '', kind },
      { key: 'british_semi_longhair', en: '', pt: '', kind },
      { key: 'british_shorthair', en: '', pt: '', kind },
      { key: 'british_longhair', en: '', pt: '', kind },
      { key: 'burmese', en: '', pt: '', kind },
      { key: 'burmilla', en: '', pt: '', kind },
      { key: 'california_spangled', en: '', pt: '', kind },
      { key: 'chantilly_tiffany', en: '', pt: '', kind },
      { key: 'chartreux', en: '', pt: '', kind },
      { key: 'chausie', en: '', pt: '', kind },
      { key: 'cheetoh', en: '', pt: '', kind },
      { key: 'colorpoint_shorthair', en: '', pt: '', kind },
      { key: 'cornish_rex', en: '', pt: '', kind },
      { key: 'cymric', en: '', pt: '', kind },
      { key: 'cyprus', en: '', pt: '', kind },
      { key: 'devon_rex', en: '', pt: '', kind },
      { key: 'donskoy', en: '', pt: '', kind },
      { key: 'dragon_li', en: '', pt: '', kind },
      { key: 'dwarf_cat', en: '', pt: '', kind },
      { key: 'egyptian_mau', en: '', pt: '', kind },
      { key: 'european_shorthair', en: '', pt: '', kind },
      { key: 'exotic_shorthair', en: '', pt: '', kind },
      { key: 'foldex', en: '', pt: '', kind },
      { key: 'german_rex', en: '', pt: '', kind },
      { key: 'havana_brown', en: '', pt: '', kind },
      { key: 'highlander', en: '', pt: '', kind },
      { key: 'himalayan', en: '', pt: '', kind },
      { key: 'japanese_bobtail', en: '', pt: '', kind },
      { key: 'javanese', en: '', pt: '', kind },
      { key: 'karelian_bobtail', en: '', pt: '', kind },
      { key: 'khao_manee', en: '', pt: '', kind },
      { key: 'korat', en: '', pt: '', kind },
      { key: 'korean_bobtail', en: '', pt: '', kind },
      { key: 'korn_ja', en: '', pt: '', kind },
      { key: 'kurilian_bobtail', en: '', pt: '', kind },
      { key: 'laperm', en: '', pt: '', kind },
      { key: 'lykoi', en: '', pt: '', kind },
      { key: 'maine_coon', en: '', pt: '', kind },
      { key: 'manx', en: '', pt: '', kind },
      { key: 'mekong_bobtail', en: '', pt: '', kind },
      { key: 'minskin', en: '', pt: '', kind },
      { key: 'munchkin', en: '', pt: '', kind },
      { key: 'nebelung', en: '', pt: '', kind },
      { key: 'napoleon', en: '', pt: '', kind },
      { key: 'norwegian_forest_cat', en: '', pt: '', kind },
      { key: 'ocicat', en: '', pt: '', kind },
      { key: 'ojos_azules', en: '', pt: '', kind },
      { key: 'oregon_rex', en: '', pt: '', kind },
      { key: 'oriental_bicolor', en: '', pt: '', kind },
      { key: 'oriental_shorthair', en: '', pt: '', kind },
      { key: 'oriental_longhair', en: '', pt: '', kind },
      { key: 'perfold', en: '', pt: '', kind },
      { key: 'persian_modern_persian_cat', en: '', pt: '', kind },
      { key: 'persian_traditional_persian_cat', en: '', pt: '', kind },
      { key: 'peterbald', en: '', pt: '', kind },
      { key: 'pixie_bob', en: '', pt: '', kind },
      { key: 'raas', en: '', pt: '', kind },
      { key: 'ragamuffin', en: '', pt: '', kind },
      { key: 'ragdoll', en: '', pt: '', kind },
      { key: 'russian_blue', en: '', pt: '', kind },
      { key: 'russian_white_black_and_tabby', en: '', pt: '', kind },
      { key: 'sam_sawet', en: '', pt: '', kind },
      { key: 'savannah', en: '', pt: '', kind },
      { key: 'scottish_fold', en: '', pt: '', kind },
      { key: 'selkirk_rex', en: '', pt: '', kind },
      { key: 'serengeti', en: '', pt: '', kind },
      { key: 'serrade_petit', en: '', pt: '', kind },
      { key: 'siamese', en: '', pt: '', kind },
      { key: 'siberian', en: '', pt: '', kind },
      { key: 'singapura', en: '', pt: '', kind },
      { key: 'snowshoe', en: '', pt: '', kind },
      { key: 'sokoke', en: '', pt: '', kind },
      { key: 'somali', en: '', pt: '', kind },
      { key: 'sphynx', en: '', pt: '', kind },
      { key: 'suphalak', en: '', pt: '', kind },
      { key: 'thai', en: '', pt: '', kind },
      { key: 'thai_lilac', en: '', pt: '', kind },
      { key: 'tiffany', en: '', pt: '', kind },
      { key: 'tonkinese', en: '', pt: '', kind },
      { key: 'toyger', en: '', pt: '', kind },
      { key: 'turkish_angora', en: '', pt: '', kind },
      { key: 'turkish_van', en: '', pt: '', kind },
      { key: 'ukrainian_levkoy', en: '', pt: '', kind },
      { key: 'york_chocolate', en: '', pt: '', kind },
    ])
  }

  public async down(query: QueryRunner) {

  }
}
