import {
  QueryRunner,
  MigrationInterface
} from 'typeorm'

import { Kind } from '../../module/breed/entity/kind.enum'
import { Breed } from '../../module/breed/entity/breed.entity'

export class Breed_1656380584269 implements MigrationInterface {
  async up(query: QueryRunner) {
    await query.manager.save(Breed, [
      { key: 'abyssinian', en: 'Abyssinian Cat', pt: 'Gato Abissínio', kind: Kind.CAT },
      { key: 'aegean', en: 'Aegean Cat', pt: 'Gato Egeu', kind: Kind.CAT },
      { key: 'american_curl', en: 'American Curl', pt: 'Curl Americano', kind: Kind.CAT },
      { key: 'american_bobtail', en: 'American Bobtail', pt: 'Bobtail Americano', kind: Kind.CAT },
      { key: 'american_shorthair', en: 'American Shorthair', pt: 'Pelo Curto Americano', kind: Kind.CAT },
      { key: 'american_wirehair', en: 'American Wirehair', pt: 'American Wirehair', kind: Kind.CAT },
      { key: 'arabian_mau', en: 'Arabian Mau', pt: 'Mau Árabe', kind: Kind.CAT },
      { key: 'australian_mist', en: 'Australian Mist', pt: 'Mist Australiano', kind: Kind.CAT },
      { key: 'asian', en: 'Asian', pt: 'Asiático', kind: Kind.CAT },
      { key: 'asian_semi_longhair', en: 'Asian Semi-longhair', pt: 'Asiático de Pelo Semi-Longo', kind: Kind.CAT },
      { key: 'balinese', en: 'Balinese', pt: 'Balinês', kind: Kind.CAT },
      { key: 'bambino', en: 'Bambino', pt: 'Bambino', kind: Kind.CAT },
      { key: 'bengal', en: 'Bengal Cat', pt: 'Bengal', kind: Kind.CAT },
      { key: 'birman', en: 'Birman', pt: 'Sagrado da Birmânia', kind: Kind.CAT },
      { key: 'bombay', en: 'Bombay Cat', pt: 'Bombaim', kind: Kind.CAT },
      { key: 'brazilian_shorthair', en: 'Brazilian Shorthair', pt: 'Gato de Pelo Curto Brasileiro', kind: Kind.CAT },
      { key: 'british_semi_longhair', en: 'British Semi-longhair', pt: 'British Semi-longhair', kind: Kind.CAT },
      { key: 'british_shorthair', en: 'British Shorthair', pt: 'Gato de Pelo Curto Inglês', kind: Kind.CAT },
      { key: 'british_longhair', en: 'British Longhair', pt: 'British Longhair', kind: Kind.CAT },
      { key: 'burmese', en: 'Burmese Cat', pt: 'Gato Birmanês', kind: Kind.CAT },
      { key: 'burmilla', en: 'Burmilla', pt: 'Burmilla', kind: Kind.CAT },
      { key: 'california_spangled', en: 'California Spangled', pt: 'California Spangled', kind: Kind.CAT },
      { key: 'chantilly_tiffany', en: 'Chantilly-Tiffany', pt: 'Chantilly-Tiffany', kind: Kind.CAT },
      { key: 'chartreux', en: 'Chartreux', pt: 'Chartreux', kind: Kind.CAT },
      { key: 'chausie', en: 'Chausie', pt: 'Chausie', kind: Kind.CAT },
      { key: 'cheetoh', en: 'Cheetoh', pt: 'Cheetoh', kind: Kind.CAT },
      { key: 'colorpoint_shorthair', en: 'Colorpoint Shorthair', pt: 'Colorpoint Shorthair', kind: Kind.CAT },
      { key: 'cornish_rex', en: 'Cornish Rex', pt: 'Cornish Rex', kind: Kind.CAT },
      { key: 'cymric', en: 'Cymric', pt: 'Cymric', kind: Kind.CAT },
      { key: 'cyprus', en: 'Cyprus Cat', pt: 'Gato de Chipre', kind: Kind.CAT },
      { key: 'devon_rex', en: 'Devon rex', pt: 'Devon rex', kind: Kind.CAT },
      { key: 'donskoy', en: 'Donskoy', pt: 'Donskoy', kind: Kind.CAT },
      { key: 'dragon_li', en: 'Dragon Li', pt: 'Dragão Li', kind: Kind.CAT },
      { key: 'dwarf_cat', en: 'Dwarf Cat', pt: 'Gato Anão', kind: Kind.CAT },
      { key: 'egyptian_mau', en: 'Egyptian Mau', pt: 'Mau Egípcio', kind: Kind.CAT },
      { key: 'european_shorthair', en: 'European Shorthair', pt: 'Gato de Pelo Curto Europeu', kind: Kind.CAT },
      { key: 'exotic_shorthair', en: 'Exotic Shorthair', pt: 'Gato Exótico', kind: Kind.CAT },
      { key: 'foldex', en: 'Foldex', pt: 'Foldex', kind: Kind.CAT },
      { key: 'german_rex', en: 'German Rex', pt: 'Rex Alemão', kind: Kind.CAT },
      { key: 'havana_brown', en: 'Havana Brown', pt: 'Havana Brown', kind: Kind.CAT },
      { key: 'highlander', en: 'Highlander', pt: 'Highlander', kind: Kind.CAT },
      { key: 'himalayan', en: 'Himalayan Cat', pt: 'Himalaio', kind: Kind.CAT },
      { key: 'japanese_bobtail', en: 'Japanese Bobtail', pt: 'Bobtail japonês', kind: Kind.CAT },
      { key: 'javanese', en: 'Javanese', pt: 'Javanês', kind: Kind.CAT },
      { key: 'karelian_bobtail', en: 'Karelian Bobtail', pt: 'Karelian Bobtail', kind: Kind.CAT },
      { key: 'khao_manee', en: 'Khao Manee', pt: 'Khao Manee', kind: Kind.CAT },
      { key: 'korat', en: 'Korat', pt: 'Korat', kind: Kind.CAT },
      { key: 'korean_bobtail', en: 'Korean Bobtail', pt: 'Korean Bobtail', kind: Kind.CAT },
      { key: 'korn_ja', en: 'Korn Ja', pt: 'Korn Ja', kind: Kind.CAT },
      { key: 'kurilian_bobtail', en: 'Kurilian Bobtail', pt: 'Kurilian Bobtail', kind: Kind.CAT },
      { key: 'laperm', en: 'LaPerm', pt: 'LaPerm', kind: Kind.CAT },
      { key: 'lykoi', en: 'Lykoi', pt: 'Lykoi', kind: Kind.CAT },
      { key: 'maine_coon', en: 'Maine Coon', pt: 'Maine Coon', kind: Kind.CAT },
      { key: 'manx', en: 'Manx', pt: 'Manx', kind: Kind.CAT },
      { key: 'mekong_bobtail', en: 'Mekong Bobtail', pt: 'Mekong Bobtail', kind: Kind.CAT },
      { key: 'minskin', en: 'Minskin', pt: 'Minskin', kind: Kind.CAT },
      { key: 'munchkin', en: 'Munchkin', pt: 'Munchkin', kind: Kind.CAT },
      { key: 'nebelung', en: 'Nebelung', pt: 'Nebelung', kind: Kind.CAT },
      { key: 'napoleon', en: 'Napoleon', pt: 'Napoleon', kind: Kind.CAT },
      { key: 'norwegian_forest_cat', en: 'Norwegian Forest cat', pt: 'Gato Norueguês da Floresta', kind: Kind.CAT },
      { key: 'ocicat', en: 'Ocicat', pt: 'Ocicat', kind: Kind.CAT },
      { key: 'ojos_azules', en: 'Ojos Azules', pt: 'Ojos Azules', kind: Kind.CAT },
      { key: 'oriental_bicolor', en: 'Oriental Bicolor', pt: 'Bicolor Oriental', kind: Kind.CAT },
      { key: 'oriental_shorthair', en: 'Oriental Shorthair', pt: 'Oriental Shorthair', kind: Kind.CAT },
      { key: 'oriental_longhair', en: 'Oriental Longhair', pt: 'Oriental Longhair', kind: Kind.CAT },
      { key: 'persian_cat', en: 'Persian Cat', pt: 'Persa', kind: Kind.CAT },
      { key: 'peterbald', en: 'Peterbald', pt: 'Peterbald', kind: Kind.CAT },
      { key: 'pixie_bob', en: 'Pixie-bob', pt: 'Pixie-bob', kind: Kind.CAT },
      { key: 'raas', en: 'Raas', pt: 'Raas', kind: Kind.CAT },
      { key: 'ragamuffin', en: 'Ragamuffin', pt: 'Ragamuffin', kind: Kind.CAT },
      { key: 'ragdoll', en: 'Ragdoll', pt: 'Ragdoll', kind: Kind.CAT },
      { key: 'russian_blue', en: 'Russian Blue', pt: 'Gato Azul Russo', kind: Kind.CAT },
      { key: 'savannah', en: 'Savannah Cat', pt: 'Gato Savannah', kind: Kind.CAT },
      { key: 'scottish_fold', en: 'Scottish Fold', pt: 'Scottish Fold', kind: Kind.CAT },
      { key: 'selkirk_rex', en: 'Selkirk Rex', pt: 'Selkirk Rex', kind: Kind.CAT },
      { key: 'serengeti', en: 'Serengeti Cat', pt: 'Gato Serengeti', kind: Kind.CAT },
      { key: 'siamese', en: 'Siamese', pt: 'Siamês', kind: Kind.CAT },
      { key: 'siberian', en: 'Siberian Cat', pt: 'Siberiano', kind: Kind.CAT },
      { key: 'singapura', en: 'Singapura Cat', pt: 'Singapura', kind: Kind.CAT },
      { key: 'snowshoe', en: 'Snowshoe', pt: 'Snowshoe', kind: Kind.CAT },
      { key: 'sokoke', en: 'Sokoke', pt: 'Sokoke', kind: Kind.CAT },
      { key: 'somali', en: 'Somali Cat', pt: 'Gato Somali', kind: Kind.CAT },
      { key: 'sphynx', en: 'Sphynx', pt: 'Sphynx', kind: Kind.CAT },
      { key: 'suphalak', en: 'Suphalak', pt: 'Suphalak', kind: Kind.CAT },
      { key: 'thai', en: 'Thai', pt: 'Thai', kind: Kind.CAT },
      { key: 'tonkinese', en: 'Tonkinese Cat', pt: 'Tonquinês', kind: Kind.CAT },
      { key: 'toyger', en: 'Toyger', pt: 'Toyger', kind: Kind.CAT },
      { key: 'turkish_angora', en: 'Turkish Angora', pt: 'Angorá', kind: Kind.CAT },
      { key: 'turkish_van', en: 'Turkish Van', pt: 'Van Turco', kind: Kind.CAT },
      { key: 'ukrainian_levkoy', en: 'Ukrainian Levkoy', pt: 'Levkoy Ucraniano', kind: Kind.CAT }
    ])

    await query.manager.save(Breed, [
      { key: 'affenpinscher', en: 'Affenpinscher', pt: 'Affenpinscher', kind: Kind.DOG },
      { key: 'afghan_hound', en: 'Afghan Hound', pt: 'Galgo afegão', kind: Kind.DOG },
      { key: 'afghan_shepherd', en: 'Afghan Shepherd', pt: 'Pastor afegão', kind: Kind.DOG },
      { key: 'aidi', en: 'Aidi', pt: 'Aidi', kind: Kind.DOG },
      { key: 'airedale_terrier', en: 'Airedale Terrier', pt: 'Airedale Terrier', kind: Kind.DOG },
      { key: 'akbash', en: 'Akbash', pt: 'Akbash', kind: Kind.DOG },
      { key: 'akita', en: 'Akita', pt: 'Akita', kind: Kind.DOG },
      { key: 'alano_espanol', en: 'Alano Español', pt: 'Alano Espanhol', kind: Kind.DOG },
      { key: 'alaskan_husky', en: 'Alaskan Husky', pt: 'Husky do Alasca', kind: Kind.DOG },
      { key: 'alaskan_klee_kai', en: 'Alaskan Klee Kai', pt: 'Alaskan Klee Kai', kind: Kind.DOG },
      { key: 'alaskan_malamute', en: 'Alaskan Malamute', pt: 'Malamute do Alasca', kind: Kind.DOG },
      { key: 'alopekis', en: 'Alopekis', pt: 'Alopekis', kind: Kind.DOG },
      { key: 'alpine_dachsbracke', en: 'Alpine Dachsbracke', pt: 'Basset Alpino', kind: Kind.DOG },
      { key: 'american_akita', en: 'American Akita', pt: 'Akita Americano', kind: Kind.DOG },
      { key: 'american_bulldog', en: 'American Bulldog', pt: 'Buldogue Americano', kind: Kind.DOG },
      { key: 'american_cocker_spaniel', en: 'American Cocker Spaniel', pt: 'Cocker Spaniel Americano', kind: Kind.DOG },
      { key: 'american_english_coonhound', en: 'American English Coonhound', pt: 'Coonhound Inglês', kind: Kind.DOG },
      { key: 'american_eskimo_dog', en: 'American Eskimo Dog', pt: 'Cão Esquimó Americano', kind: Kind.DOG },
      { key: 'american_foxhound', en: 'American Foxhound', pt: 'Foxhound Americano', kind: Kind.DOG },
      { key: 'american_hairless_terrier', en: 'American Hairless Terrier', pt: 'Terrier Pelado Americano', kind: Kind.DOG },
      { key: 'american_pit_bull_terrier', en: 'American Pit Bull Terrier', pt: 'American Pit Bull Terrier', kind: Kind.DOG },
      { key: 'american_staffordshire_terrier', en: 'American Staffordshire Terrier', pt: 'American Staffordshire Terrier', kind: Kind.DOG },
      { key: 'american_water_spaniel', en: 'American Water Spaniel', pt: "Cão d'água Americano", kind: Kind.DOG },
      { key: 'anatolian_shepherd_dog', en: 'Anatolian Shepherd Dog', pt: 'Pastor da Anatólia', kind: Kind.DOG },
      { key: 'andalusian_hound', en: 'Andalusian Hound', pt: 'Podenco Andaluz', kind: Kind.DOG },
      { key: 'anglo_francais_de_petite_venerie', en: 'Anglo-Français de Petite Vènerie', pt: 'Anglo-francês da Pequena Vénerie', kind: Kind.DOG },
      { key: 'appenzeller_sennenhund', en: 'Appenzeller Sennenhund', pt: 'Boiadeiro de Appenzell', kind: Kind.DOG },
      { key: 'ariege_pointer', en: 'Ariège Pointer', pt: 'Braco de Ariège', kind: Kind.DOG },
      { key: 'ariegeois', en: 'Ariégeois', pt: 'Cão do Ariége', kind: Kind.DOG },
      { key: 'armant', en: 'Armant', pt: 'Cão Pastor de Armant', kind: Kind.DOG },
      { key: 'armenian_gampr_dog', en: 'Armenian Gampr', pt: 'Gampr', kind: Kind.DOG },
      { key: 'artois_hound', en: 'Artois Hound', pt: 'Cão de Artois', kind: Kind.DOG },
      { key: 'australian_cattle_dog', en: 'Australian Cattle Dog', pt: 'Boiadeiro Australiano', kind: Kind.DOG },
      { key: 'australian_kelpie', en: 'Australian Kelpie', pt: 'Kelpie Australiano', kind: Kind.DOG },
      { key: 'australian_shepherd', en: 'Australian Shepherd', pt: 'Pastor Australiano', kind: Kind.DOG },
      { key: 'australian_silky_terrier', en: 'Australian Silky Terrier', pt: 'Silky Terrier Australiano', kind: Kind.DOG },
      { key: 'australian_stumpy_tail_cattle_dog', en: 'Australian Stumpy Tail Cattle Dog', pt: 'Boiadeiro Australiano de Cauda Chata', kind: Kind.DOG },
      { key: 'australian_terrier', en: 'Australian Terrier', pt: 'Terrier Australiano', kind: Kind.DOG },
      { key: 'austrian_black_and_tan_hound', en: 'Austrian Black and Tan Hound', pt: 'Sabujo-austríaco-preto-e-castanho', kind: Kind.DOG },
      { key: 'austrian_pinscher', en: 'Austrian Pinscher', pt: 'Pinscher Austríaco', kind: Kind.DOG },
      { key: 'azawakh', en: 'Azawakh', pt: 'Azawakh', kind: Kind.DOG },
      { key: 'bakharwal_dog', en: 'Bakharwal Dog', pt: 'Bakharwal', kind: Kind.DOG },
      { key: 'barbet', en: 'Barbet', pt: 'Barbet', kind: Kind.DOG },
      { key: 'basenji', en: 'Basenji', pt: 'Basenji', kind: Kind.DOG },
      { key: 'basque_shepherd_dog', en: 'Basque Shepherd Dog', pt: 'Pastor Basco', kind: Kind.DOG },
      { key: 'basset_artésien_normand', en: 'Basset Artésien Normand', pt: 'Basset Artesiano Normando', kind: Kind.DOG },
      { key: 'basset_bleu_de_gascogne', en: 'Basset Bleu de Gascogne', pt: 'Basset Azul da Gasconha', kind: Kind.DOG },
      { key: 'basset_fauve_de_bretagne', en: 'Basset Fauve de Bretagne', pt: 'Basset Fulvo da Bretanha', kind: Kind.DOG },
      { key: 'basset_griffon_vendéen_grand', en: 'Grand Basset Griffon Vendéen', pt: 'Grande Basset Griffon da Vendeia', kind: Kind.DOG },
      { key: 'basset_griffon_vendéen_petit', en: 'Petit Basset Griffon Vendéen', pt: 'Pequeno Basset Griffon da Vendeia', kind: Kind.DOG },
      { key: 'basset_hound', en: 'Basset Hound', pt: 'Basset Hound', kind: Kind.DOG },
      { key: 'bavarian_mountain_hound', en: 'Bavarian Mountain Hound', pt: 'Sabujo Montanhês da Baviera', kind: Kind.DOG },
      { key: 'beagle', en: 'Beagle', pt: 'Beagle', kind: Kind.DOG },
      { key: 'beagle_harrier', en: 'Beagle Harrier', pt: 'Beagle Harrier', kind: Kind.DOG },
      { key: 'bearded_collie', en: 'Bearded Collie', pt: 'Bearded Collie', kind: Kind.DOG },
      { key: 'beauceron', en: 'Beauceron', pt: 'Pastor-de-beauce', kind: Kind.DOG },
      { key: 'bedlington_terrier', en: 'Bedlington Terrier', pt: 'Bedlington Terrier', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_groenendael', en: 'Belgian Shepherd Groenendael', pt: 'Pastor Belga Groenendael', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_laekenois', en: 'Belgian Shepherd Laekenois', pt: 'Pastor Belga Laekenois', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_malinois', en: 'Belgian Shepherd Malinois', pt: 'Pastor Belga Malinois', kind: Kind.DOG },
      { key: 'belgian_shepherd_dog_tervuren', en: 'Belgian Shepherd Tervueren', pt: 'Tervuren', kind: Kind.DOG },
      { key: 'bergamasco_shepherd', en: 'Bergamasco Sheepdog', pt: 'Pastor Bergamasco', kind: Kind.DOG },
      { key: 'berger_blanc_suisse', en: 'Berger Blanc Suisse', pt: 'Pastor Branco Suíço', kind: Kind.DOG },
      { key: 'berger_picard', en: 'Berger Picards', pt: 'Pastor da Picardia', kind: Kind.DOG },
      { key: 'bernese_mountain_dog', en: 'Bernese Mountain Dog', pt: 'Bernese', kind: Kind.DOG },
      { key: 'bichon_frise', en: 'Bichon Frise Dog', pt: 'Bichon Frisé', kind: Kind.DOG },
      { key: 'billy', en: 'Billy', pt: 'Billy', kind: Kind.DOG },
      { key: 'black_and_tan_coonhound', en: 'Black and Tan Coonhound', pt: 'Coonhound Preto e Castanho', kind: Kind.DOG },
      { key: 'black_and_tan_virginia_foxhound', en: 'Black and Tan Virginia Foxhound', pt: 'Black and Tan Virginia Foxhound', kind: Kind.DOG },
      { key: 'black_norwegian_elkhound', en: 'Black Norwegian Elkhound', pt: 'Elkhound Norueguês Preto', kind: Kind.DOG },
      { key: 'black_russian_terrier', en: 'Black Russian Terrier', pt: 'Terrier Preto da Rússia', kind: Kind.DOG },
      { key: 'black_mouth_cur', en: 'Black Mouth Cur', pt: 'Black Mouth Cur', kind: Kind.DOG },
      { key: 'bleu_de_gascogne_grand', en: 'Grand Bleu de Gascogne', pt: 'Grande Azul da Gasconha', kind: Kind.DOG },
      { key: 'bleu_de_gascogne_petit', en: 'Petit Bleu de Gascogne', pt: 'Pequeno Azul da Gasconha', kind: Kind.DOG },
      { key: 'bloodhound', en: 'Bloodhound', pt: 'Bloodhound', kind: Kind.DOG },
      { key: 'blue_lacy', en: 'Blue Lacy', pt: 'Blue Lacy', kind: Kind.DOG },
      { key: 'blue_picardy_spaniel', en: 'Blue Picardy Spaniel', pt: 'Spaniel Azul da Picardia', kind: Kind.DOG },
      { key: 'bluetick_coonhound', en: 'Bluetick Coonhound', pt: 'Bluetick Coonhound', kind: Kind.DOG },
      { key: 'boerboel', en: 'Boerboel', pt: 'Boerboel', kind: Kind.DOG },
      { key: 'bohemian_shepherd', en: 'Bohemian Shepherd', pt: 'Pastor Boêmio', kind: Kind.DOG },
      { key: 'bolognese', en: 'Bolognese', pt: 'Bichon Bolonhês', kind: Kind.DOG },
      { key: 'border_collie', en: 'Border Collie', pt: 'Border Collie', kind: Kind.DOG },
      { key: 'border_terrier', en: 'Border Terrier', pt: 'Border Terrier', kind: Kind.DOG },
      { key: 'borzoi', en: 'Borzoi', pt: 'Borzoi', kind: Kind.DOG },
      { key: 'bosnian_coarse_haired_hound', en: 'Bosnian Coarse-haired Hound', pt: 'Sabujo da Bósnia', kind: Kind.DOG },
      { key: 'boston_terrier', en: 'Boston Terrier', pt: 'Boston Terrier', kind: Kind.DOG },
      { key: 'bouvier_des_ardennes', en: 'Bouvier des Ardennes', pt: 'Boiadeiro das Ardenas', kind: Kind.DOG },
      { key: 'bouvier_des_flandres', en: 'Bouvier des Flandres', pt: 'Boiadeiro de Flandres', kind: Kind.DOG },
      { key: 'boxer', en: 'Boxer', pt: 'Boxer', kind: Kind.DOG },
      { key: 'boykin_spaniel', en: 'Boykin Spaniel', pt: 'Boykin Spaniel', kind: Kind.DOG },
      { key: 'bracco_italiano', en: 'Bracco Italiano', pt: 'Braco Italiano', kind: Kind.DOG },
      { key: 'braque_dAuvergne', en: "Braque d'Auvergne", pt: 'Braco de Auvérnia', kind: Kind.DOG },
      { key: 'braque_du_bourbonnais', en: 'Braque du Bourbonnais', pt: 'Braco de Burbônia', kind: Kind.DOG },
      { key: 'braque_du_puy', en: 'Braque du Puy', pt: 'Braco Dupuy', kind: Kind.DOG },
      { key: 'braque_francais', en: 'Braque Français', pt: 'Braco Francês', kind: Kind.DOG },
      { key: 'braque_saint_germain', en: 'Braque Saint-Germain', pt: 'Braco de Saint-Germain', kind: Kind.DOG },
      { key: 'brazilian_dogo', en: 'Dogue Brasileiro', pt: 'Dogue Brasileiro', kind: Kind.DOG },
      { key: 'brazilian_terrier', en: 'Brazilian Terrier', pt: 'Terrier Brasileiro', kind: Kind.DOG },
      { key: 'briard', en: 'Briard', pt: 'Pastor-de-brie', kind: Kind.DOG },
      { key: 'briquet_griffon_vendéen', en: 'Briquet Griffon Vendéen', pt: 'Braco Griffon da Vendeia', kind: Kind.DOG },
      { key: 'brittany', en: 'Brittany', pt: 'Spaniel Bretão', kind: Kind.DOG },
      { key: 'broholmer', en: 'Broholmer', pt: 'Broholmer', kind: Kind.DOG },
      { key: 'bruno_jura_hound', en: 'Bruno Jura Hound', pt: 'Bruno Jura Hound', kind: Kind.DOG },
      { key: 'bucovina_shepherd_dog', en: 'Bucovina Shepherd Dog', pt: 'Pastor do Sudeste Europeu', kind: Kind.DOG },
      { key: 'bull_terrier', en: 'Bull Terrier', pt: 'Bull Terrier', kind: Kind.DOG },
      { key: 'bull_terrier_miniature', en: 'Miniature Bull Terrier', pt: 'Bull Terrier Miniatura', kind: Kind.DOG },
      { key: 'bulldog', en: 'Bulldog', pt: 'Buldogue', kind: Kind.DOG },
      { key: 'bullmastiff', en: 'Bullmastiff', pt: 'Bulmastife', kind: Kind.DOG },
      { key: 'bully_kutta', en: 'Bully Kutta', pt: 'Bully Kutta', kind: Kind.DOG },
      { key: 'burgos_pointer', en: 'Burgos Pointer', pt: 'Perdigueiro de Burgos', kind: Kind.DOG },
      { key: 'cairn_terrier', en: 'Cairn Terrier', pt: 'Cairn Terrier', kind: Kind.DOG },
      { key: 'canaan_dog', en: 'Canaan Dog', pt: 'Cão de Canaã', kind: Kind.DOG },
      { key: 'canadian_eskimo_dog', en: 'Canadian Eskimo Dog', pt: 'Cão Esquimó Canadense', kind: Kind.DOG },
      { key: 'cane_corso', en: 'Cane Corso', pt: 'Cane Corso', kind: Kind.DOG },
      { key: 'cantabrian_water_dog', en: 'Cantabrian Water Dog', pt: "Cão d'água Espanhol", kind: Kind.DOG },
      { key: 'cao_da_Serra_de_aires', en: 'Portuguese Sheepdog', pt: 'Cão da Serra de Aires', kind: Kind.DOG },
      { key: 'cao_de_castro_laboreiro', en: 'Castro Laboreiro Dog', pt: 'Cão de Castro Laboreiro', kind: Kind.DOG },
      { key: 'cao_de_gado_transmontano', en: 'Cão de Gado Transmontano', pt: 'Cão de Gado Transmontano', kind: Kind.DOG },
      { key: 'cao_fila_de_sao_miguel', en: 'Saint Miguel Cattle Dog', pt: 'Cão de Fila de São Miguel', kind: Kind.DOG },
      { key: 'carolina dog', en: 'Carolina Dog', pt: 'Carolina Dog', kind: Kind.DOG },
      { key: 'carpathian_shepherd_dog', en: 'Carpathian Shepherd Dog', pt: 'Pastor Romeno dos Cárpatos', kind: Kind.DOG },
      { key: 'catahoula_leopard_dog', en: 'Catahoula Leopard Dog', pt: 'Catahoula Cur', kind: Kind.DOG },
      { key: 'catalan_sheepdog', en: 'Catalan Sheepdog', pt: 'Pastor Catalão', kind: Kind.DOG },
      { key: 'caucasian_shepherd_dog', en: 'Caucasian Shepherd Dog', pt: 'Pastor do Cáucaso', kind: Kind.DOG },
      { key: 'cavalier_king_charles_spaniel', en: 'Cavalier King Charles Spaniel', pt: 'Cavalier King Charles Spaniel', kind: Kind.DOG },
      { key: 'central_asian_shepherd_dog', en: 'Central Asian Shepherd Dog', pt: 'Pastor da Ásia central', kind: Kind.DOG },
      { key: 'cesky_fousek', en: 'Cesky Fousek', pt: 'Cesky Fousek', kind: Kind.DOG },
      { key: 'cesky_terrier', en: 'Cesky Terrier', pt: 'Cesky Terrier', kind: Kind.DOG },
      { key: 'chesapeake_bay_retriever', en: 'Chesapeake Bay Retriever', pt: 'Chesapeake Bay Retriever', kind: Kind.DOG },
      { key: 'chien_français_blanc_et_noir', en: 'Chien Francais Blanc et Noir', pt: 'Branco e Preto Francês', kind: Kind.DOG },
      { key: 'chien_français_blanc_et_orange', en: 'Chien Français Blanc et Orange', pt: 'Branco e Laranja Francês', kind: Kind.DOG },
      { key: 'chien_français_tricolore', en: 'Chien Français Tricolore', pt: 'Sabujo Tricolor Francês', kind: Kind.DOG },
      { key: 'chihuahua', en: 'Chihuahua', pt: 'Chihuahua', kind: Kind.DOG },
      { key: 'chilean_fox_terrier', en: 'Chilean Fox Terrier', pt: 'Fox Terrier Chileno', kind: Kind.DOG },
      { key: 'chinese_chongqing_dog', en: 'Chongqing dog', pt: 'Cão chinês de chongqing', kind: Kind.DOG },
      { key: 'chinese_crested_dog', en: 'Chinese Crested', pt: 'Cão de Crista Chinês', kind: Kind.DOG },
      { key: 'chinook', en: 'Chinook', pt: 'Chinook', kind: Kind.DOG },
      { key: 'chippiparai', en: 'Chippiparai', pt: 'Chippiparai', kind: Kind.DOG },
      { key: 'chow_chow', en: 'Chow Chow', pt: 'Chow Chow', kind: Kind.DOG },
      { key: 'cierny_sery', en: 'Cierny Sery', pt: 'Cierny Sery', kind: Kind.DOG },
      { key: 'cirneco_dellEtna', en: "Cirneco dell'Etna", pt: 'Cirneco do Etna', kind: Kind.DOG },
      { key: 'clumber_spaniel', en: 'Clumber Spaniel', pt: 'Clumber Spaniel', kind: Kind.DOG },
      { key: 'collie_rough', en: 'Rough Collie', pt: 'Collie Pelo Longo', kind: Kind.DOG },
      { key: 'collie_smooth', en: 'Smooth Collie', pt: 'Collie de Pelo Curto', kind: Kind.DOG },
      { key: 'combai', en: 'Kombai', pt: 'Combai', kind: Kind.DOG },
      { key: 'coton_de_tulear', en: 'Coton de Tulear', pt: 'Coton de Tulear', kind: Kind.DOG },
      { key: 'cretan_hound', en: 'Cretan Hound', pt: 'Galgo Farejador de Creta', kind: Kind.DOG },
      { key: 'croatian_sheepdog', en: 'Croatian Sheepdog', pt: 'Pastor Croata', kind: Kind.DOG },
      { key: 'curly_coated_retriever', en: 'Curly-Coated Retriever', pt: 'Curly-Coated Retriever', kind: Kind.DOG },
      { key: 'cursinu', en: 'Cursinu', pt: 'Cursinu', kind: Kind.DOG },
      { key: 'czechoslovakian_wolfdog', en: 'Czechoslovakian Wolfdog', pt: 'Cão Lobo Tchecoslovaco', kind: Kind.DOG },
      { key: 'dachshund', en: 'Dachshund', pt: 'Dachshund', kind: Kind.DOG },
      { key: 'dalmatian', en: 'Dalmatian', pt: 'Dálmata', kind: Kind.DOG },
      { key: 'dandie_dinmont_terrier', en: 'Dandie Dinmont Terrier', pt: 'Dandie Dinmont Terrier', kind: Kind.DOG },
      { key: 'danish_swedish_farmdog', en: 'Danish-Swedish Farmdog', pt: 'Cão Fazendeiro da Dinamarca e Suécia', kind: Kind.DOG },
      { key: 'deutsche_bracke', en: 'Deutsche Bracke', pt: 'Braco Alemão', kind: Kind.DOG },
      { key: 'doberman_pinscher', en: 'Doberman Pinscher', pt: 'Dobermann', kind: Kind.DOG },
      { key: 'dogo_argentino', en: 'Dogo Argentino', pt: 'Dogo Argentino', kind: Kind.DOG },
      { key: 'dogue_de_bordeaux', en: 'Dogue de Bordeaux', pt: 'Dogue de Bordeaux', kind: Kind.DOG },
      { key: 'drentse_patrijshond', en: 'Drentsche Patrijshond', pt: 'Spaniel Perdigueiro de Drente', kind: Kind.DOG },
      { key: 'drever', en: 'Drever', pt: 'Drever', kind: Kind.DOG },
      { key: 'dunker', en: 'Dunker', pt: 'Dunker', kind: Kind.DOG },
      { key: 'dutch_shepherd', en: 'Dutch Shepherd', pt: 'Pastor Holandês', kind: Kind.DOG },
      { key: 'dutch_smoushond', en: 'Dutch Smoushond', pt: 'Smoushond Holandês', kind: Kind.DOG },
      { key: 'east_siberian_laika', en: 'East Siberian Laika', pt: 'Laika da Sibéria Oriental', kind: Kind.DOG },
      { key: 'east_european_shepherd', en: 'East European Shepherd', pt: 'Pastor do Leste Europeu', kind: Kind.DOG },
      { key: 'elo', en: 'Elo', pt: 'Elo', kind: Kind.DOG },
      { key: 'english_cocker_spaniel', en: 'English Cocker Spaniel', pt: 'Cocker Spaniel Inglês', kind: Kind.DOG },
      { key: 'english_foxhound', en: 'English Foxhound', pt: 'Foxhound Inglês', kind: Kind.DOG },
      { key: 'english_mastiff', en: 'English Mastiff', pt: 'Mastim Inglês', kind: Kind.DOG },
      { key: 'english_setter', en: 'English Setter', pt: 'Setter Inglês', kind: Kind.DOG },
      { key: 'english_shepherd', en: 'English Shepherd', pt: 'Pastor Inglês', kind: Kind.DOG },
      { key: 'english_springer_spaniel', en: 'English Springer Spaniel', pt: 'Springer Spaniel inglês', kind: Kind.DOG },
      { key: 'english_toy_terrier', en: 'English Toy Terrier', pt: 'English Toy Terrier', kind: Kind.DOG },
      { key: 'entlebucher_mountain_dog', en: 'Entlebucher Mountain Dog', pt: 'Boiadeiro de Entlebuch', kind: Kind.DOG },
      { key: 'estonian_hound', en: 'Estonian Hound', pt: 'Estonian Hound', kind: Kind.DOG },
      { key: 'estrela_mountain_dog', en: 'Estrela Mountain Dog', pt: 'Cão da Serra da Estrela', kind: Kind.DOG },
      { key: 'eurasier', en: 'Eurasier', pt: 'Eurasier', kind: Kind.DOG },
      { key: 'eurohound', en: 'Eurohound', pt: 'Eurohound', kind: Kind.DOG },
      { key: 'field_spaniel', en: 'Field Spaniel', pt: 'Field Spaniel', kind: Kind.DOG },
      { key: 'fila_brasileiro', en: 'Fila Brasileiro', pt: 'Fila Brasileiro', kind: Kind.DOG },
      { key: 'finnish_hound', en: 'Finnish Hound', pt: 'Sabujo Finlandês', kind: Kind.DOG },
      { key: 'finnish_lapphund', en: 'Finnish Lapphund', pt: 'Pastor Finlandês da Lapônia', kind: Kind.DOG },
      { key: 'finnish_spitz', en: 'Finnish Spitz', pt: 'Spitz Finlandês', kind: Kind.DOG },
      { key: 'flat_coated_retriever', en: 'Flat-Coated Retriever', pt: 'Flat-Coated Retriever', kind: Kind.DOG },
      { key: 'fox_terrier_smooth', en: 'Smooth Fox Terrier', pt: 'Fox Terrier Pelo Liso', kind: Kind.DOG },
      { key: 'fox_terrier_wire', en: 'Wire Fox Terrier', pt: 'Fox Terrier Pelo Duro', kind: Kind.DOG },
      { key: 'french_brittany', en: 'French Brittany', pt: 'Spaniel Bretão', kind: Kind.DOG },
      { key: 'french_bulldog', en: 'French Bulldog', pt: 'Buldogue Francês', kind: Kind.DOG },
      { key: 'french_spaniel', en: 'French Spaniel', pt: 'Spaniel Francês', kind: Kind.DOG },
      { key: 'galgo_espanol', en: 'Spanish galgo', pt: 'Galgo Espanhol', kind: Kind.DOG },
      { key: 'garafian_shepherd', en: 'Garafian Shepherd', pt: 'Pastor Garafiano', kind: Kind.DOG },
      { key: 'gascon_saintongeois', en: 'Gascon Saintongeois', pt: 'Gascão Saintongeois', kind: Kind.DOG },
      { key: 'georgian_shepherd_dog', en: 'Georgian Shepherd Dog', pt: 'Pastor-da-geórgia', kind: Kind.DOG },
      { key: 'german_longhaired_pointer', en: 'German Longhaired Pointer', pt: 'Braco Alemão de Pelo Longo', kind: Kind.DOG },
      { key: 'german_pinscher', en: 'German Pinscher', pt: 'Pinscher Alemão', kind: Kind.DOG },
      { key: 'german_roughhaired_pointer', en: 'German Roughhaired Pointer', pt: 'Braco Alemão Pelo Duro', kind: Kind.DOG },
      { key: 'german_shepherd_dog', en: 'German Shepherd', pt: 'Pastor-alemão', kind: Kind.DOG },
      { key: 'german_shorthaired_pointer', en: 'German Shorthaired Pointer', pt: 'Braco Alemão de Pelo Curto', kind: Kind.DOG },
      { key: 'german_spaniel', en: 'German Spaniel', pt: 'Perdigueiro Alemão', kind: Kind.DOG },
      { key: 'german_spitz', en: 'German Spitz', pt: 'Spitz Alemão', kind: Kind.DOG },
      { key: 'giant_schnauzer', en: 'Giant Schnauzer', pt: 'Schnauzer Gigante', kind: Kind.DOG },
      { key: 'glen_of_imaal_terrier', en: 'Glen of Imaal Terrier', pt: 'Terrier Irlandês do Glen do Imaal', kind: Kind.DOG },
      { key: 'golden_retriever', en: 'Golden Retriever', pt: 'Golden Retriever', kind: Kind.DOG },
      { key: 'gordon_setter', en: 'Gordon Setter', pt: 'Setter Gordon', kind: Kind.DOG },
      { key: 'grand_anglo_français_blanc_et_noir', en: 'Grand Anglo-Français Blanc Et Noir', pt: 'Grande Anglo-Francês Branco e Preto', kind: Kind.DOG },
      { key: 'grand_anglo_français_blanc_et_orange', en: 'Grand Anglo-Français Blanc et Orange', pt: 'Grande Anglo-Francês Branco e Laranja', kind: Kind.DOG },
      { key: 'grand_anglo_français_tricolore', en: 'Grand Anglo-Français Tricolore', pt: 'Grande Anglo-Francês Tricolor', kind: Kind.DOG },
      { key: 'grand_griffon_vendeen', en: 'Grand Griffon Vendeen', pt: 'Grande griffon da Vendeia', kind: Kind.DOG },
      { key: 'great_dane', en: 'Great Dane', pt: 'Dogue Alemão', kind: Kind.DOG },
      { key: 'great_pyrenees', en: 'Great Pyrenees', pt: 'Cão de Montanha dos Pirenéus', kind: Kind.DOG },
      { key: 'greater_swiss_mountain_dog', en: 'Greater Swiss Mountain Dog', pt: 'Grande Boiadeiro Suíço', kind: Kind.DOG },
      { key: 'hellenic_hound', en: 'Hellenic Hound', pt: 'Sabujo Helênico', kind: Kind.DOG },
      { key: 'greenland_dog', en: 'Greenland Dog', pt: 'Cão da Groenlândia', kind: Kind.DOG },
      { key: 'greyhound', en: 'Greyhound', pt: 'Galgo Inglês', kind: Kind.DOG },
      { key: 'griffon_bleu_de_gascogne', en: 'Griffon Bleu de Gascogne', pt: 'Griffon Azul da Gasconha', kind: Kind.DOG },
      { key: 'griffon_bruxellois', en: 'Brussels Griffon', pt: 'Griffon de Bruxelas', kind: Kind.DOG },
      { key: 'griffon_fauve_de_bretagne', en: 'Griffon Fauve De Bretagne', pt: 'Griffon Fauve de Bretagne', kind: Kind.DOG },
      { key: 'griffon_nivernais', en: 'Griffon Nivernais', pt: 'Griffon de Nivernais', kind: Kind.DOG },
      { key: 'guatemalan_dogo', en: 'Guatemalan Dogo', pt: 'Dogo Guatemalteco', kind: Kind.DOG },
      { key: 'hamiltonstovare', en: 'Hamiltonstovare', pt: 'Sabujo de Hamilton', kind: Kind.DOG },
      { key: 'hanover_hound', en: 'Hanover Hound', pt: 'Cão-Farejador-de-Hanôver', kind: Kind.DOG },
      { key: 'harrier', en: 'Harrier', pt: 'Harrier', kind: Kind.DOG },
      { key: 'havanese', en: 'Havanese', pt: 'Havanese', kind: Kind.DOG },
      { key: 'himalayan_sheepdog', en: 'Himalayan Sheepdog', pt: 'Pastor do Himalaia', kind: Kind.DOG },
      { key: 'hokkaido', en: 'Hokkaido', pt: 'Hokkaido', kind: Kind.DOG },
      { key: 'hovawart', en: 'Hovawart', pt: 'Hovawart', kind: Kind.DOG },
      { key: 'huntaway', en: 'Huntaway', pt: 'Pastor de Nova Zelândia', kind: Kind.DOG },
      { key: 'hygenhund', en: 'Hygen Hound', pt: 'Sabujo de Hygen', kind: Kind.DOG },
      { key: 'ibizan_hound', en: 'Ibizan Hound', pt: 'Podengo Ibicenco', kind: Kind.DOG },
      { key: 'icelandic_sheepdog', en: 'Icelandic Sheepdog', pt: 'Cão Islandês de Pastoreio', kind: Kind.DOG },
      { key: 'indian_pariah_dog', en: 'Indian Pariah Dog', pt: 'Indian Pariah Dog', kind: Kind.DOG },
      { key: 'indian_spitz', en: 'Indian Spitz', pt: 'Spitz Indiano', kind: Kind.DOG },
      { key: 'irish_red_and_white_setter', en: 'Irish Red and White Setter', pt: 'Setter Irlandês Ruivo e Branco', kind: Kind.DOG },
      { key: 'irish_setter', en: 'Irish Setter', pt: 'Setter Irlandês', kind: Kind.DOG },
      { key: 'irish_terrier', en: 'Irish Terrier', pt: 'Terrier Irlandês', kind: Kind.DOG },
      { key: 'irish_water_spaniel', en: 'Irish Water Spaniel', pt: "Spaniel D'água Irlandês", kind: Kind.DOG },
      { key: 'irish_wolfhound', en: 'Irish Wolfhound', pt: 'Lébrel Irlandês', kind: Kind.DOG },
      { key: 'istrian_coarse_haired_hound', en: 'Istrian Coarse-haired Hound', pt: 'Sabujo da Ístria de Pelo Duro', kind: Kind.DOG },
      { key: 'istrian_shorthaired_hound', en: 'Istrian Shorthaired Hound', pt: 'Sabujo da Ístria de Pelo Curto', kind: Kind.DOG },
      { key: 'italian_greyhound', en: 'Italian Greyhound', pt: 'Galguinho Italiano', kind: Kind.DOG },
      { key: 'jack_russell_terrier', en: 'Jack Russell Terrier', pt: 'Jack Russell Terrier', kind: Kind.DOG },
      { key: 'jagdterrier', en: 'Jagdterrier', pt: 'Terrier Alemão de Caça', kind: Kind.DOG },
      { key: 'jamthund', en: 'Jämthund', pt: 'Cão Sueco de Caça ao Cervo', kind: Kind.DOG },
      { key: 'japanese_chin', en: 'Japanese Chin', pt: 'Spaniel Japonês', kind: Kind.DOG },
      { key: 'japanese_spitz', en: 'Japanese Spitz', pt: 'Spitz Japonês', kind: Kind.DOG },
      { key: 'japanese_terrier', en: 'Japanese Terrier', pt: 'Terrier Japonês', kind: Kind.DOG },
      { key: 'kaikadi', en: 'Kaikadi', pt: 'Kaikadi', kind: Kind.DOG },
      { key: 'kai_ken', en: 'Kai Ken', pt: 'Kai', kind: Kind.DOG },
      { key: 'kangal_dog', en: 'Kangal Dog', pt: 'Kangal', kind: Kind.DOG },
      { key: 'kanni', en: 'Kanni', pt: 'Kanni', kind: Kind.DOG },
      { key: 'karakachan_dog', en: 'Karakachan Dog', pt: 'Karakachan', kind: Kind.DOG },
      { key: 'karelian_bear_dog', en: 'Karelian Bear Dog', pt: 'Cão de Ursos da Carélia', kind: Kind.DOG },
      { key: 'karst_shepherd', en: 'Karst Shepherd', pt: 'Pastor-de-kraski', kind: Kind.DOG },
      { key: 'keeshond', en: 'Keeshond', pt: 'Keeshond', kind: Kind.DOG },
      { key: 'kerry_beagle', en: 'Kerry Beagle', pt: 'Kerry Beagle', kind: Kind.DOG },
      { key: 'kerry_blue_terrier', en: 'Kerry Blue Terrier', pt: 'Kerry Blue Terrier', kind: Kind.DOG },
      { key: 'king_charles_spaniel', en: 'Cavalier King Charles Spaniel', pt: 'Cavalier King Charles Spaniel', kind: Kind.DOG },
      { key: 'king_shepherd', en: 'King Shepherd', pt: 'Pastor Rei', kind: Kind.DOG },
      { key: 'kintamani', en: 'Kintamani', pt: 'Kintamani', kind: Kind.DOG },
      { key: 'kishu_ken', en: 'Kishu Ken', pt: 'Kishu', kind: Kind.DOG },
      { key: 'komondor', en: 'Komondor', pt: 'Komondor', kind: Kind.DOG },
      { key: 'kooikerhondje', en: 'Kooikerhondje', pt: 'Pequeno Cão Holandês', kind: Kind.DOG },
      { key: 'koolie', en: 'Koolie', pt: 'Koolie', kind: Kind.DOG },
      { key: 'kokoni', en: 'Kokoni', pt: 'Kokoni', kind: Kind.DOG },
      { key: 'korean_jindo', en: 'Korean Jindo', pt: 'Jindo-coreano', kind: Kind.DOG },
      { key: 'kromfohrlander', en: 'Kromfohrlander', pt: 'Kromfohrlander', kind: Kind.DOG },
      { key: 'kuvasz', en: 'Kuvasz', pt: 'Kuvasz', kind: Kind.DOG },
      { key: 'labrador_retriever', en: 'Labrador Retriever', pt: 'Labrador Retriever', kind: Kind.DOG },
      { key: 'lagotto_romagnolo', en: 'Lagotto Romagnolo', pt: 'Lagotto Romagnolo', kind: Kind.DOG },
      { key: 'lakeland_terrier', en: 'Lakeland Terrier', pt: 'Lakeland Terrier', kind: Kind.DOG },
      { key: 'lancashire_heeler', en: 'Lancashire Heeler', pt: 'Lancashire Heeler', kind: Kind.DOG },
      { key: 'landseer', en: 'Landseer', pt: 'Landseer', kind: Kind.DOG },
      { key: 'lapponian_herder', en: 'Lapponian Herder', pt: 'Pastor Finlandês da Lapônia', kind: Kind.DOG },
      { key: 'leonberger', en: 'Leonberger', pt: 'Leonberger', kind: Kind.DOG },
      { key: 'lhasa_apso', en: 'Lhasa Apso', pt: 'Lhasa Apso', kind: Kind.DOG },
      { key: 'lithuanian_hound', en: 'Lithuanian Hound', pt: 'Lithuanian Hound', kind: Kind.DOG },
      { key: 'lowchen', en: 'Löwchen', pt: 'Pequeno Cão Leão', kind: Kind.DOG },
      { key: 'magyar_agar', en: 'Magyar agár', pt: 'Galgo Húngaro', kind: Kind.DOG },
      { key: 'majorca_ratter', en: 'Majorca Ratter', pt: 'Majorca Ratter', kind: Kind.DOG },
      { key: 'majorca_shepherd_dog', en: 'Majorca Shepherd Dog', pt: 'Pastor-maiorquino', kind: Kind.DOG },
      { key: 'maltese', en: 'Maltese', pt: 'Maltês', kind: Kind.DOG },
      { key: 'manchester_terrier', en: 'Manchester Terrier', pt: 'Manchester Terrier', kind: Kind.DOG },
      { key: 'maremma_sheepdog', en: 'Maremma Sheepdog', pt: 'Pastor Maremano Abruzês', kind: Kind.DOG },
      { key: 'mcNab', en: 'McNab', pt: 'McNab', kind: Kind.DOG },
      { key: 'mexican_hairless_dog', en: 'Mexican Hairless Dog', pt: 'Pelado Mexicano', kind: Kind.DOG },
      { key: 'miniature_american_shepherd', en: 'Miniature American Shepherd', pt: 'Pastor Americano Miniatura', kind: Kind.DOG },
      { key: 'miniature_fox_terrier', en: 'Miniature Fox Terrier', pt: 'Toy Fox Terrier', kind: Kind.DOG },
      { key: 'miniature_pinscher', en: 'Miniature Pinscher', pt: 'Pinscher Miniatura', kind: Kind.DOG },
      { key: 'miniature_schnauzer', en: 'Miniature Schnauzer', pt: 'Schnauzer Miniatura', kind: Kind.DOG },
      { key: 'romanian_mioritic_shepherd_dog', en: 'Romanian Mioritic Shepherd Dog', pt: 'Pastor Romeno Miorítico', kind: Kind.DOG },
      { key: 'montenegrin_mountain_hound', en: 'Montenegrin Mountain Hound', pt: 'Sabujo Montanhês Montenegrino', kind: Kind.DOG },
      { key: 'moscow_watchdog', en: 'Moscow Watchdog', pt: 'Cão de Guarda de Moscou', kind: Kind.DOG },
      { key: 'mountain_cur', en: 'Mountain Cur', pt: 'Mountain Cur', kind: Kind.DOG },
      { key: 'mudhol_hound', en: 'Mudhol Hound', pt: 'Mudhol Hound', kind: Kind.DOG },
      { key: 'mudi', en: 'Mudi', pt: 'Mudi', kind: Kind.DOG },
      { key: 'munsterlander_large', en: 'Large Munsterlander', pt: 'Grande Munsterlander', kind: Kind.DOG },
      { key: 'munsterlander_small', en: 'Small Munsterlander', pt: 'Pequeno Munsterlander', kind: Kind.DOG },
      { key: 'neapolitan_mastiff', en: 'Neapolitan Mastiff', pt: 'Mastim Napolitano', kind: Kind.DOG },
      { key: 'newfoundland', en: 'Newfoundland', pt: 'Terra Nova', kind: Kind.DOG },
      { key: 'new_zealand_heading_dog', en: 'New Zealand Heading Dog', pt: 'New Zealand Heading Dog', kind: Kind.DOG },
      { key: 'norfolk_terrier', en: 'Norfolk Terrier', pt: 'Norfolk Terrier', kind: Kind.DOG },
      { key: 'norrbottenspets', en: 'Norrbottenspets', pt: 'Spitz de Norboten', kind: Kind.DOG },
      { key: 'northern_inuit_dog', en: 'Northern Inuit Dog', pt: 'Inuit do Norte', kind: Kind.DOG },
      { key: 'norwegian_buhund', en: 'Norwegian Buhund', pt: 'Buhund Norueguês', kind: Kind.DOG },
      { key: 'norwegian_elkhound', en: 'Norwegian Elkhound', pt: 'Elkhound', kind: Kind.DOG },
      { key: 'norwegian_lundehund', en: 'Norwegian Lundehund', pt: 'Norwegian Lundehund', kind: Kind.DOG },
      { key: 'norwich_terrier', en: 'Norwich Terrier', pt: 'Norwich Terrier', kind: Kind.DOG },
      { key: 'nova_scotia_duck_tolling_retriever', en: 'Nova Scotia Duck Tolling Retriever', pt: 'Retriever da Nova Escócia', kind: Kind.DOG },
      { key: 'old_danish_pointer', en: 'Old Danish Pointer', pt: 'Velho Braco Dinamarquês', kind: Kind.DOG },
      { key: 'old_english_sheepdog', en: 'Old English Sheepdog', pt: 'Old English Sheepdog', kind: Kind.DOG },
      { key: 'olde_english_bulldogge', en: 'Olde English Bulldogge', pt: 'Olde English Bulldogge', kind: Kind.DOG },
      { key: 'otterhound', en: 'Otterhound', pt: 'Otterhound', kind: Kind.DOG },
      { key: 'pachon_navarro', en: 'Pachón Navarro', pt: 'Pachón Navarro', kind: Kind.DOG },
      { key: 'papillon', en: 'Papillon', pt: 'Papillon', kind: Kind.DOG },
      { key: 'parson_russell_terrier', en: 'Parson Russell Terrier', pt: 'Parson Russell Terrier', kind: Kind.DOG },
      { key: 'patterdale_terrier', en: 'Patterdale Terrier', pt: 'Patterdale Terrier', kind: Kind.DOG },
      { key: 'pekingese', en: 'Pekingese', pt: 'Pequinês', kind: Kind.DOG },
      { key: 'perro_de_presa_canario', en: 'Perro de Presa Canario', pt: 'Presa Canário', kind: Kind.DOG },
      { key: 'perro_de_presa_mallorquin', en: 'Perro de Presa Mallorquin', pt: 'Cão de Presa Maiorquino', kind: Kind.DOG },
      { key: 'peruvian_hairless_dog', en: 'Peruvian Hairless Dog', pt: 'Cão Pelado Peruano', kind: Kind.DOG },
      { key: 'phalene', en: 'Phalène', pt: 'Phalène', kind: Kind.DOG },
      { key: 'pharaoh_hound', en: 'Pharaoh Hound', pt: 'Pharaoh Hound', kind: Kind.DOG },
      { key: 'phu_quoc_ridgeback', en: 'Phu Quoc Ridgeback', pt: 'Phu Quoc Ridgeback', kind: Kind.DOG },
      { key: 'picardy_spaniel', en: 'Picardy Spaniel', pt: 'Spaniel da Picardia', kind: Kind.DOG },
      { key: 'plott_hound', en: 'Plott Hound', pt: 'Plott Hound', kind: Kind.DOG },
      { key: 'podenco_canario', en: 'Podenco Canario', pt: 'Podengo Canário', kind: Kind.DOG },
      { key: 'pointer', en: 'Pointer', pt: 'Pointer', kind: Kind.DOG },
      { key: 'poitevin', en: 'Poitevin', pt: 'Poitevin', kind: Kind.DOG },
      { key: 'polish_greyhound', en: 'Polish Greyhound', pt: 'Galgo Polaco', kind: Kind.DOG },
      { key: 'polish_hound', en: 'Polish Hound', pt: 'Braco Polonês', kind: Kind.DOG },
      { key: 'polish_hunting_dog', en: 'Polish Hunting Dog', pt: 'Cão de Caça Polonês', kind: Kind.DOG },
      { key: 'polish_lowland_sheepdog', en: 'Polish Lowland Sheepdog', pt: 'Pastor Polonês da Planície', kind: Kind.DOG },
      { key: 'polish_tatra_sheepdog', en: 'Polish Tatra Sheepdog', pt: 'Pastor-de-tatra', kind: Kind.DOG },
      { key: 'pomeranian', en: 'Pomeranian', pt: 'Lulu da Pomerânia', kind: Kind.DOG },
      { key: 'pont_audemer_spaniel', en: 'Pont-Audemer Spaniel', pt: 'Spaniel de Pon-Audemar', kind: Kind.DOG },
      { key: 'poodle', en: 'Poodle', pt: 'Poodle', kind: Kind.DOG },
      { key: 'porcelaine', en: 'Porcelaine', pt: 'Porcelana', kind: Kind.DOG },
      { key: 'portuguese_podengo', en: 'Portuguese Podengo', pt: 'Podengo Português', kind: Kind.DOG },
      { key: 'portuguese_pointer', en: 'Portuguese Pointer', pt: 'Perdigueiro Português', kind: Kind.DOG },
      { key: 'portuguese_water_dog', en: 'Portuguese Water Dog', pt: 'Cão de Água Português', kind: Kind.DOG },
      { key: 'posavac_hound', en: 'Posavac Hound', pt: 'Sabujo de Posavac', kind: Kind.DOG },
      { key: 'prazsky_krysarik', en: 'Prazsky Krysarik', pt: 'Prazsky Krysarik', kind: Kind.DOG },
      { key: 'pudelpointer', en: 'Pudelpointer', pt: 'Pudelpointer', kind: Kind.DOG },
      { key: 'pug', en: 'Pug', pt: 'Pug', kind: Kind.DOG },
      { key: 'puli', en: 'Puli', pt: 'Puli', kind: Kind.DOG },
      { key: 'pumi', en: 'Pumi', pt: 'Pumi', kind: Kind.DOG },
      { key: 'pungsan_dog', en: 'Pungsan Dog', pt: 'Pungsan', kind: Kind.DOG },
      { key: 'pyrenean_mastiff', en: 'Pyrenean Mastiff', pt: 'Mastim dos Pirenéus', kind: Kind.DOG },
      { key: 'pyrenean_shepherd', en: 'Pyrenean Shepherd', pt: 'Pastor dos Pirineus', kind: Kind.DOG },
      { key: 'rafeiro_do_alentejo', en: 'Rafeiro do Alentejo', pt: 'Rafeiro do Alentejo', kind: Kind.DOG },
      { key: 'rajapalayam', en: 'Rajapalayam', pt: 'Rajapalayam', kind: Kind.DOG },
      { key: 'rampur_greyhound', en: 'Rampur Greyhound', pt: 'Rampur Greyhound', kind: Kind.DOG },
      { key: 'rastreador_brasileiro', en: 'Rastreador Brasileiro', pt: 'Rastreador Brasileiro', kind: Kind.DOG },
      { key: 'ratonero_bodeguero_andaluz', en: 'Ratonero Bodeguero Andaluz', pt: 'Ratonero Bodeguero Andaluz', kind: Kind.DOG },
      { key: 'ratonero_valenciano', en: 'Ratonero Valenciano', pt: 'Ratonero Valenciano', kind: Kind.DOG },
      { key: 'rat_terrier', en: 'Rat Terrier', pt: 'Rat Terrier', kind: Kind.DOG },
      { key: 'redbone_coonhound', en: 'Redbone Coonhound', pt: 'Redbone Coonhound', kind: Kind.DOG },
      { key: 'rhodesian_ridgeback', en: 'Rhodesian Ridgeback', pt: 'Rhodesian Ridgeback', kind: Kind.DOG },
      { key: 'rottweiler', en: 'Rottweiler', pt: 'Rottweiler', kind: Kind.DOG },
      { key: 'russian_spaniel', en: 'Russian Spaniel', pt: 'Spaniel Russo', kind: Kind.DOG },
      { key: 'russian_toy', en: 'Russian Toy', pt: 'Pequeno Cão Russo', kind: Kind.DOG },
      { key: 'russo_european_laika', en: 'Russo-European Laika', pt: 'Laika Russo Europeu', kind: Kind.DOG },
      { key: 'saarloos_wolfdog', en: 'Saarloos wolfdog', pt: 'Cão-Lobo de Saarloos', kind: Kind.DOG },
      { key: 'sabueso_espanol', en: 'Sabueso Español', pt: 'Sabujo Espanhol', kind: Kind.DOG },
      { key: 'saint_usuge_spaniel', en: 'Saint-Usuge Spaniel', pt: 'Saint-Usuge Spaniel', kind: Kind.DOG },
      { key: 'saluki', en: 'Saluki', pt: 'Saluki', kind: Kind.DOG },
      { key: 'samoyed', en: 'Samoyed', pt: 'Samoieda', kind: Kind.DOG },
      { key: 'sapsali', en: 'Sapsali', pt: 'Sapsali', kind: Kind.DOG },
      { key: 'sarplaninac', en: 'Sarplaninac', pt: 'Pastor-jugoslavo', kind: Kind.DOG },
      { key: 'schapendoes', en: 'Schapendoes', pt: 'Schapendoes', kind: Kind.DOG },
      { key: 'schillerstovare', en: 'Schiller Hound', pt: 'Schillerstovare', kind: Kind.DOG },
      { key: 'schipperke', en: 'Schipperke', pt: 'Schipperke', kind: Kind.DOG },
      { key: 'standard_schnauzer', en: 'Standard Schnauzers', pt: 'Schnauzer Standard', kind: Kind.DOG },
      { key: 'schweizer_laufhund', en: 'Schweizer Laufhund', pt: 'Laufhund', kind: Kind.DOG },
      { key: 'scottish_deerhound', en: 'Scottish Deerhound', pt: 'Deerhound', kind: Kind.DOG },
      { key: 'scottish_terrier', en: 'Scottish Terrier', pt: 'Terrier Escocês', kind: Kind.DOG },
      { key: 'sealyham_terrier', en: 'Sealyham Terrier', pt: 'Sealyham Terrier', kind: Kind.DOG },
      { key: 'segugio_italiano', en: 'Segugio Italiano', pt: 'Sabujo Italiano', kind: Kind.DOG },
      { key: 'serbian_hound', en: 'Serbian Hound', pt: 'Sabujo Sérvio', kind: Kind.DOG },
      { key: 'serbian_tricolour_hound', en: 'Serbian Tricolor Hound', pt: 'Sabujo Tricolor Sérvio', kind: Kind.DOG },
      { key: 'shar_pei', en: 'Shar Pei', pt: 'Shar Pei', kind: Kind.DOG },
      { key: 'shetland_sheepdog', en: 'Shetland Sheepdog', pt: 'Pastor de Shetland', kind: Kind.DOG },
      { key: 'shiba_inu', en: 'Shiba Inu', pt: 'Shiba Inu', kind: Kind.DOG },
      { key: 'shih_tzu', en: 'Shih Tzu', pt: 'Shih Tzu', kind: Kind.DOG },
      { key: 'shikoku', en: 'Shikoku', pt: 'Shikoku Inu', kind: Kind.DOG },
      { key: 'shiloh_shepherd', en: 'Shiloh Shepherd', pt: 'Pastor Shiloh', kind: Kind.DOG },
      { key: 'siberian_husky', en: 'Siberian Husky', pt: 'Husky Siberiano', kind: Kind.DOG },
      { key: 'silken_windhound', en: 'Silken Windhound', pt: 'Silken Windhound', kind: Kind.DOG },
      { key: 'sinhala_hound', en: 'Sinhala Hound', pt: 'Sinhala Hound', kind: Kind.DOG },
      { key: 'skye_terrier', en: 'Skye Terrier', pt: 'Skye Terrier', kind: Kind.DOG },
      { key: 'sloughi', en: 'Sloughi', pt: 'Sloughi', kind: Kind.DOG },
      { key: 'slovak_cuvac', en: 'Slovensky Cuvac', pt: 'Cuvac Eslovaco', kind: Kind.DOG },
      { key: 'slovakian_rough_haired_pointer', en: 'Slovak Rough-haired Pointer', pt: 'Braco Eslovaco de Pelo Duro', kind: Kind.DOG },
      { key: 'slovensky_kopov', en: 'Slovensky Kopov', pt: 'Sabujo Eslovaco', kind: Kind.DOG },
      { key: 'smalandsstovare', en: 'Smalandsstovare', pt: 'Smalandsstovare', kind: Kind.DOG },
      { key: 'soft_coated_wheaten_terrier', en: 'Soft Coated Wheaten Terrier', pt: 'Soft Coated Wheaten Terrier', kind: Kind.DOG },
      { key: 'south_russian_ovcharka', en: 'South Russian Ovcharka', pt: 'Pastor-da-rússia-meridional', kind: Kind.DOG },
      { key: 'spanish_mastiff', en: 'Spanish Mastiff', pt: 'Mastim Espanhol', kind: Kind.DOG },
      { key: 'spanish_water_dog', en: 'Spanish Water Dog', pt: "Cão d'água Espanhol", kind: Kind.DOG },
      { key: 'spinone_italiano', en: 'Spinone Italiano', pt: 'Spinone Italiano', kind: Kind.DOG },
      { key: 'sporting_lucas_terrier', en: 'Sporting Lucas Terrier', pt: 'Sporting Lucas Terrier', kind: Kind.DOG },
      { key: 'st_bernard', en: 'Saint Bernard', pt: 'São Bernardo', kind: Kind.DOG },
      { key: 'stabyhoun', en: 'Stabyhoun', pt: 'Cão de Aponte Frisão', kind: Kind.DOG },
      { key: 'staffordshire_bull_terrier', en: 'Staffordshire Bull Terrier', pt: 'Staffordshire Bull Terrier', kind: Kind.DOG },
      { key: 'stephens_cur', en: 'Stephens Cur', pt: 'Stephens Cur', kind: Kind.DOG },
      { key: 'styrian_coarse_haired_hound', en: 'Styrian Coarse-haired Hound', pt: 'Braco da Estíria de Pelo Duro', kind: Kind.DOG },
      { key: 'sussex_spaniel', en: 'Sussex Spaniel', pt: 'Sussex Spaniel', kind: Kind.DOG },
      { key: 'swedish_lapphund', en: 'Swedish Lapphund', pt: 'Lapphund', kind: Kind.DOG },
      { key: 'swedish_vallhund', en: 'Swedish Vallhund', pt: 'Vallhund Sueco', kind: Kind.DOG },
      { key: 'taigan', en: 'Taigan', pt: 'Taigan', kind: Kind.DOG },
      { key: 'taiwan_dog', en: 'Taiwan Dog', pt: 'Cão de Taiwan', kind: Kind.DOG },
      { key: 'tamaskan_dog', en: 'Tamaskan', pt: 'Tamaskan', kind: Kind.DOG },
      { key: 'teddy_roosevelt_terrier', en: 'Teddy Roosevelt Terrier', pt: 'Teddy Roosevelt Terrier', kind: Kind.DOG },
      { key: 'telomian', en: 'Telomian', pt: 'Telomian', kind: Kind.DOG },
      { key: 'tenterfield_terrier', en: 'Tenterfield Terrier', pt: 'Terrier de Tenterfield', kind: Kind.DOG },
      { key: 'thai_bangkaew_dog', en: 'Thai Bangkaew', pt: 'Bangkaew', kind: Kind.DOG },
      { key: 'thai_ridgeback', en: 'Thai Ridgeback', pt: 'Thai Ridgeback', kind: Kind.DOG },
      { key: 'tibetan_mastiff', en: 'Tibetan Mastiff', pt: 'Mastim Tibetano', kind: Kind.DOG },
      { key: 'tibetan_spaniel', en: 'Tibetan Spaniel', pt: 'Spaniel Tibetano', kind: Kind.DOG },
      { key: 'tibetan_terrier', en: 'Tibetan Terrier', pt: 'Terrier Tibetano', kind: Kind.DOG },
      { key: 'tornjak', en: 'Tornjak', pt: 'Tornjak', kind: Kind.DOG },
      { key: 'tosa', en: 'Tosa Inu', pt: 'Tosa Inu', kind: Kind.DOG },
      { key: 'toy_fox_terrier', en: 'Toy Fox Terrier', pt: 'Toy Fox Terrier', kind: Kind.DOG },
      { key: 'toy_manchester_terrier', en: 'Toy Manchester Terrier', pt: 'Toy Manchester Terrier', kind: Kind.DOG },
      { key: 'transylvanian_hound', en: 'Transylvanian Hound', pt: 'Braco-da-transilvânia', kind: Kind.DOG },
      { key: 'treeing_cur', en: 'Treeing Cur', pt: 'Treeing Cur', kind: Kind.DOG },
      { key: 'treeing_tennessee_brindle', en: 'Treeing Tennessee Brindle', pt: 'Treeing Tennessee Brindle', kind: Kind.DOG },
      { key: 'treeing_walker_coonhound', en: 'Treeing Walker Coonhound', pt: 'Treeing Walker Coonhound', kind: Kind.DOG },
      { key: 'tyrolean_hound', en: 'Tyrolean Hound', pt: 'Braco tirolês', kind: Kind.DOG },
      { key: 'cimarron_uruguayo', en: 'Cimarrón Uruguayo', pt: 'Cimarrón Uruguayo', kind: Kind.DOG },
      { key: 'valencian_terrier', en: 'Valencian Terrier', pt: 'Ratonero Valenciano', kind: Kind.DOG },
      { key: 'villano_de_las_encartaciones', en: 'Villano de Las Encartaciones', pt: 'Villano de Las Encartaciones', kind: Kind.DOG },
      { key: 'vizsla', en: 'Vizsla', pt: 'Braco Húngaro de Pelo Curto', kind: Kind.DOG },
      { key: 'volpino_italiano', en: 'Volpino Italiano', pt: 'Volpino Italiano', kind: Kind.DOG },
      { key: 'weimaraner', en: 'Weimaraner', pt: 'Weimaraner', kind: Kind.DOG },
      { key: 'welsh_corgi_cardigan', en: 'Cardigan Welsh Corgi', pt: 'Welsh Corgi Cardigan', kind: Kind.DOG },
      { key: 'welsh_corgi_pembroke', en: 'Pembroke Welsh Corgi', pt: 'Welsh corgi Pembroke', kind: Kind.DOG },
      { key: 'welsh_sheepdog', en: 'Welsh Sheepdog', pt: 'Pastor de Gales', kind: Kind.DOG },
      { key: 'welsh_springer_spaniel', en: 'Welsh Springer Spaniel', pt: 'Springer Spaniel de Gales', kind: Kind.DOG },
      { key: 'welsh_terrier', en: 'Welsh Terrier', pt: 'Welsh Terrier', kind: Kind.DOG },
      { key: 'west_highland_white_terrier', en: 'West Highland White Terrier', pt: 'West Highland White Terrier', kind: Kind.DOG },
      { key: 'west_siberian_laika', en: 'West Siberian Laika', pt: 'Laika da Sibéria Ocidental', kind: Kind.DOG },
      { key: 'westphalian_dachsbracke', en: 'Westphalian Dachsbracke', pt: 'Basset Alemão da Vestfália', kind: Kind.DOG },
      { key: 'wetterhoun', en: 'Wetterhoun', pt: "Cão d'água Frisão", kind: Kind.DOG },
      { key: 'whippet', en: 'Whippet', pt: 'Whippet', kind: Kind.DOG },
      { key: 'white_shepherd', en: 'White Shepherd', pt: 'Pastor Branco', kind: Kind.DOG },
      { key: 'wirehaired_pointing_griffon', en: 'Wirehaired Pointing Griffon', pt: 'Griffon de Aponte de Pelo Duro', kind: Kind.DOG },
      { key: 'wirehaired_vizsla', en: 'Wirehaired Vizslas', pt: 'Braco Húngaro de Pelo Duro', kind: Kind.DOG },
      { key: 'xiasi_dog', en: 'Xiasi Dog', pt: 'Xiasi Dog', kind: Kind.DOG },
      { key: 'yorkshire_terrier', en: 'Yorkshire Terrier', pt: 'Yorkshire Terrier', kind: Kind.DOG }
    ])
  }

  async down(query: QueryRunner) {
    await query.clearTable('breed')
  }
}
