name: Build App

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: yarn install
      - name: format check
        run: yarn format:check
      - name: build
        run: yarn build
