name: Deploy App

on:
  push:
    branches: main

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: publish
        uses: kciter/aws-ecr-action@v4
        with:
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ vars.AWS_DEFAULT_REGION }}

        #   repo: ${{ vars.AWS_ECR_REPOSITORY }}
        #   path: ./app
        #   dockerfile: ./app/Dockerfile
